import { db, fs, watchIdentity, profileById, avatarSvg, safeText } from '/game/assets/js/eras-data.js';
const $=s=>document.querySelector(s);const params=new URLSearchParams(location.search);const lobbyId=params.get('lobby')||'';const worldId=lobbyId?`lobby:${lobbyId}`:'global';
const state={identity:null,x:50,y:50,vx:0,vy:0,lastFrame:performance.now(),lastWrite:0,lastHeartbeat:0,dirty:false,presenceUnsub:null,profiles:new Map(),remote:new Map(),keys:new Set(),touch:new Set(),tokenMap:new Map()};
const message=m=>$('#globalMessage').textContent=String(m).toUpperCase();
function presenceId(profileId){return `${profileId}__${worldId}`.replace(/\//g,'_');}
async function loadWorldName(){if(!lobbyId){$('#worldName').textContent='GLOBAL PLAZA';return;}try{const snap=await fs.getDoc(fs.doc(db,'gameLobbies',lobbyId));if(snap.exists()){$('#worldName').textContent=snap.data().name||'HOSTED GAME';const member=state.identity?.profileId;if(member)await fs.setDoc(fs.doc(db,'gameLobbies',lobbyId,'members',member),{profileId:member,role:snap.data().hostProfileId===member?'host':'player',joinedAt:fs.serverTimestamp(),lastSeenAt:fs.serverTimestamp()});}}catch(e){console.error(e);}}
async function getProfile(id){if(state.profiles.has(id))return state.profiles.get(id);const p=await profileById(id);if(p)state.profiles.set(id,p);return p;}
function ensureToken(id,profile,isLocal=false){let el=state.tokenMap.get(id);if(el)return el;el=document.createElement('div');el.className=`player-token${isLocal?' is-local':''}`;el.dataset.profileId=id;const avatar=document.createElement('div');avatar.className='player-avatar';avatar.innerHTML=avatarSvg(profile||{displayName:'Member'});const name=document.createElement('span');name.className='player-name';name.textContent=profile?.displayName||'Member';el.append(avatar,name);$('#globalMap').appendChild(el);state.tokenMap.set(id,el);return el;}
function updateToken(el,x,y){el.style.left=`${Math.max(2,Math.min(98,x))}%`;el.style.top=`${Math.max(3,Math.min(96,y))}%`;}
async function renderRemote(){const now=Date.now();for(const [id,p] of [...state.remote]){if(id===state.identity?.profileId)continue;const ts=p.updatedAt?.toMillis?.()||0;if(ts&&now-ts>25000){state.remote.delete(id);state.tokenMap.get(id)?.remove();state.tokenMap.delete(id);continue;}const profile=await getProfile(id);const el=ensureToken(id,profile,false);const elapsed=ts?Math.min(3,(now-ts)/1000):0;updateToken(el,Number(p.x||50)+Number(p.vx||0)*elapsed,Number(p.y||50)+Number(p.vy||0)*elapsed);}}
function watchPresence(){state.presenceUnsub?.();const q=fs.query(fs.collection(db,'gamePresence'),fs.where('worldId','==',worldId));state.presenceUnsub=fs.onSnapshot(q,snap=>{state.remote.clear();snap.forEach(d=>state.remote.set(d.data().profileId,{id:d.id,...d.data()}));$('#worldState').textContent=`ONLINE // ${snap.size} PRESENCE RECORD${snap.size===1?'':'S'}`;renderRemote();},e=>{console.error(e);$('#worldState').textContent='FIRESTORE PRESENCE ERROR';message(`WORLD ERROR: ${e.code||e.message}`);});}
async function restorePosition(){if(!state.identity?.profileId)return;try{const ref=fs.doc(db,'gamePresence',presenceId(state.identity.profileId));const snap=await fs.getDoc(ref);if(snap.exists()&&snap.data().worldId===worldId){state.x=Number(snap.data().x||50);state.y=Number(snap.data().y||50);}const el=ensureToken(state.identity.profileId,state.identity.profile,true);updateToken(el,state.x,state.y);}catch(e){console.error(e);}}
async function flushPresence(force=false){if(!state.identity?.profileId)return;const now=performance.now();if(!force&&!state.dirty&&now-state.lastHeartbeat<20000)return;if(!force&&state.dirty&&now-state.lastWrite<3000)return;state.lastWrite=now;state.lastHeartbeat=now;state.dirty=false;try{await fs.setDoc(fs.doc(db,'gamePresence',presenceId(state.identity.profileId)),{worldId,profileId:state.identity.profileId,x:state.x,y:state.y,vx:state.vx,vy:state.vy,updatedAt:fs.serverTimestamp()});if(lobbyId)fs.updateDoc(fs.doc(db,'gameLobbies',lobbyId,'members',state.identity.profileId),{lastSeenAt:fs.serverTimestamp()}).catch(()=>{});}catch(e){console.error(e);message(`PRESENCE WRITE FAILED: ${e.code||e.message}`);}}
function direction(){const has=k=>state.keys.has(k)||state.touch.has(k);let dx=(has('right')?1:0)-(has('left')?1:0),dy=(has('down')?1:0)-(has('up')?1:0);if(dx&&dy){dx*=.7071;dy*=.7071;}return[dx,dy];}
function frame(t){const dt=Math.min(.05,(t-state.lastFrame)/1000);state.lastFrame=t;if(state.identity?.profileId){const[dx,dy]=direction();const speed=12;const nvx=dx*speed,nvy=dy*speed;if(nvx!==state.vx||nvy!==state.vy){state.vx=nvx;state.vy=nvy;state.dirty=true;}if(dx||dy){state.x=Math.max(3,Math.min(97,state.x+nvx*dt));state.y=Math.max(5,Math.min(94,state.y+nvy*dt));state.dirty=true;const el=state.tokenMap.get(state.identity.profileId);if(el)updateToken(el,state.x,state.y);}flushPresence(false);renderRemote();}requestAnimationFrame(frame);}requestAnimationFrame(frame);
const keyMap={ArrowUp:'up',w:'up',W:'up',ArrowDown:'down',s:'down',S:'down',ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right'};window.addEventListener('keydown',e=>{const k=keyMap[e.key];if(k){e.preventDefault();state.keys.add(k);}});window.addEventListener('keyup',e=>{const k=keyMap[e.key];if(k){e.preventDefault();state.keys.delete(k);state.dirty=true;flushPresence(true);}});
document.querySelectorAll('[data-move]').forEach(btn=>{const dir=btn.dataset.move;const down=e=>{e.preventDefault();state.touch.add(dir)};const up=e=>{e.preventDefault();state.touch.delete(dir);state.dirty=true;flushPresence(true)};btn.addEventListener('pointerdown',down);btn.addEventListener('pointerup',up);btn.addEventListener('pointercancel',up);btn.addEventListener('pointerleave',up);});
window.addEventListener('pagehide',()=>{if(state.identity?.profileId)fs.deleteDoc(fs.doc(db,'gamePresence',presenceId(state.identity.profileId))).catch(()=>{});});
watchIdentity(async i=>{state.identity=i;if(!i?.profileId){message('Sign in to materialize your LCS profile icon in Global.');return;}message('Your LCS avatar is live. Move with WASD, arrows, or touch.');await restorePosition();await loadWorldName();await flushPresence(true);watchPresence();});
loadWorldName();
