import { db, fs, watchIdentity, profileById, avatarSvg } from '/game/assets/js/eras-data.js';
const $=s=>document.querySelector(s);const params=new URLSearchParams(location.search);const lobbyId=params.get('lobby')||'';const worldId=lobbyId?`lobby:${lobbyId}`:'global';
const state={identity:null,x:50,y:50,vx:0,vy:0,lastFrame:performance.now(),lastWrite:0,lastHeartbeat:0,dirty:false,velocityDirty:false,presenceUnsub:null,profiles:new Map(),remote:new Map(),keys:new Set(),touch:new Set(),tokenMap:new Map()};
const message=m=>{const el=$('#globalMessage');if(el)el.textContent=String(m).toUpperCase();};
function presenceId(profileId){return `${profileId}__${worldId}`.replace(/\//g,'_');}
async function loadWorldName(){if(!lobbyId){$('#worldName').textContent='GLOBAL PLAZA';return;}try{const snap=await fs.getDoc(fs.doc(db,'gameLobbies',lobbyId));if(snap.exists()){$('#worldName').textContent=snap.data().name||'HOSTED GAME';const member=state.identity?.profileId;if(member)await fs.setDoc(fs.doc(db,'gameLobbies',lobbyId,'members',member),{profileId:member,role:snap.data().hostProfileId===member?'host':'player',joinedAt:fs.serverTimestamp(),lastSeenAt:fs.serverTimestamp()});}}catch(e){console.error(e);}}
async function getProfile(id){if(state.profiles.has(id))return state.profiles.get(id);const p=await profileById(id);if(p)state.profiles.set(id,p);return p;}
function ensureToken(id,profile,isLocal=false){let el=state.tokenMap.get(id);if(el)return el;el=document.createElement('div');el.className=`player-token${isLocal?' is-local':''}`;el.dataset.profileId=id;const avatar=document.createElement('div');avatar.className='player-avatar';avatar.innerHTML=avatarSvg(profile||{displayName:'Member'});const name=document.createElement('span');name.className='player-name';name.textContent=profile?.displayName||'Member';el.append(avatar,name);$('#globalMap').appendChild(el);state.tokenMap.set(id,el);return el;}
function updateToken(el,x,y){el.style.left=`${Math.max(2,Math.min(98,x))}%`;el.style.top=`${Math.max(3,Math.min(96,y))}%`;}
function setRemoteSnapshot(id,data){const prev=state.remote.get(id);const ts=data.updatedAt?.toMillis?.()||Date.now();const x=Number(data.x||50),y=Number(data.y||50);if(prev){prev.x=x;prev.y=y;prev.vx=Number(data.vx||0);prev.vy=Number(data.vy||0);prev.ts=ts;if(!Number.isFinite(prev.renderX))prev.renderX=x;if(!Number.isFinite(prev.renderY))prev.renderY=y;}else state.remote.set(id,{x,y,vx:Number(data.vx||0),vy:Number(data.vy||0),ts,renderX:x,renderY:y});}
async function ensureRemoteTokens(){for(const [id] of state.remote){if(id===state.identity?.profileId||state.tokenMap.has(id))continue;ensureToken(id,await getProfile(id),false);}}
function renderRemote(dt){const now=Date.now();for(const [id,p] of [...state.remote]){if(id===state.identity?.profileId)continue;if(p.ts&&now-p.ts>25000){state.remote.delete(id);state.tokenMap.get(id)?.remove();state.tokenMap.delete(id);continue;}const el=state.tokenMap.get(id);if(!el)continue;const elapsed=p.ts?Math.min(1.6,Math.max(0,(now-p.ts)/1000)):0;const tx=Math.max(2,Math.min(98,p.x+p.vx*elapsed)),ty=Math.max(3,Math.min(96,p.y+p.vy*elapsed));const dx=tx-p.renderX,dy=ty-p.renderY;if(Math.hypot(dx,dy)>18){p.renderX=tx;p.renderY=ty;}else{const blend=1-Math.exp(-10*dt);p.renderX+=dx*blend;p.renderY+=dy*blend;}updateToken(el,p.renderX,p.renderY);}}
function watchPresence(){state.presenceUnsub?.();const q=fs.query(fs.collection(db,'gamePresence'),fs.where('worldId','==',worldId));state.presenceUnsub=fs.onSnapshot(q,snap=>{const seen=new Set();snap.forEach(d=>{const data={id:d.id,...d.data()};seen.add(data.profileId);if(data.profileId!==state.identity?.profileId)setRemoteSnapshot(data.profileId,data);});for(const id of [...state.remote.keys()])if(!seen.has(id)){state.remote.delete(id);state.tokenMap.get(id)?.remove();state.tokenMap.delete(id);}$('#worldState').textContent=`ONLINE // ${snap.size} PRESENCE RECORD${snap.size===1?'':'S'}`;ensureRemoteTokens();},e=>{console.error(e);$('#worldState').textContent='FIRESTORE PRESENCE ERROR';message(`WORLD ERROR: ${e.code||e.message}`);});}
async function restorePosition(){if(!state.identity?.profileId)return;try{const ref=fs.doc(db,'gamePresence',presenceId(state.identity.profileId));const snap=await fs.getDoc(ref);if(snap.exists()&&snap.data().worldId===worldId){state.x=Number(snap.data().x||50);state.y=Number(snap.data().y||50);}updateToken(ensureToken(state.identity.profileId,state.identity.profile,true),state.x,state.y);}catch(e){console.error(e);}}
async function flushPresence(force=false){if(!state.identity?.profileId)return;const now=performance.now(),moving=state.vx!==0||state.vy!==0;if(!force&&!state.dirty&&now-state.lastHeartbeat<15000)return;const minGap=state.velocityDirty?180:(moving?1400:3000);if(!force&&state.dirty&&now-state.lastWrite<minGap)return;state.lastWrite=now;state.lastHeartbeat=now;state.dirty=false;state.velocityDirty=false;try{await fs.setDoc(fs.doc(db,'gamePresence',presenceId(state.identity.profileId)),{worldId,profileId:state.identity.profileId,x:state.x,y:state.y,vx:state.vx,vy:state.vy,updatedAt:fs.serverTimestamp()});if(lobbyId)fs.updateDoc(fs.doc(db,'gameLobbies',lobbyId,'members',state.identity.profileId),{lastSeenAt:fs.serverTimestamp()}).catch(()=>{});}catch(e){console.error(e);message(`PRESENCE WRITE FAILED: ${e.code||e.message}`);}}
function direction(){const has=k=>state.keys.has(k)||state.touch.has(k);let dx=(has('right')?1:0)-(has('left')?1:0),dy=(has('down')?1:0)-(has('up')?1:0);if(dx&&dy){dx*=.7071;dy*=.7071;}return[dx,dy];}
function frame(t){const dt=Math.min(.04,(t-state.lastFrame)/1000);state.lastFrame=t;if(state.identity?.profileId){const[dx,dy]=direction(),speed=12,nvx=dx*speed,nvy=dy*speed;if(nvx!==state.vx||nvy!==state.vy){state.vx=nvx;state.vy=nvy;state.dirty=true;state.velocityDirty=true;}if(dx||dy){state.x=Math.max(3,Math.min(97,state.x+nvx*dt));state.y=Math.max(5,Math.min(94,state.y+nvy*dt));state.dirty=true;const el=state.tokenMap.get(state.identity.profileId);if(el)updateToken(el,state.x,state.y);}flushPresence(false);renderRemote(dt);}requestAnimationFrame(frame);}requestAnimationFrame(frame);
const keyMap={ArrowUp:'up',w:'up',W:'up',ArrowDown:'down',s:'down',S:'down',ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right'};window.addEventListener('keydown',e=>{const k=keyMap[e.key];if(k){e.preventDefault();if(!state.keys.has(k)){state.keys.add(k);state.dirty=true;state.velocityDirty=true;}}});window.addEventListener('keyup',e=>{const k=keyMap[e.key];if(k){e.preventDefault();state.keys.delete(k);state.dirty=true;state.velocityDirty=true;setTimeout(()=>flushPresence(true),0);}});
document.querySelectorAll('[data-move]').forEach(btn=>{const dir=btn.dataset.move;const down=e=>{e.preventDefault();try{btn.setPointerCapture?.(e.pointerId)}catch{}state.touch.add(dir);state.dirty=true;state.velocityDirty=true;};const up=e=>{e.preventDefault();state.touch.delete(dir);state.dirty=true;state.velocityDirty=true;setTimeout(()=>flushPresence(true),0);};btn.addEventListener('pointerdown',down);btn.addEventListener('pointerup',up);btn.addEventListener('pointercancel',up);});
window.addEventListener('pagehide',()=>{if(state.identity?.profileId)fs.deleteDoc(fs.doc(db,'gamePresence',presenceId(state.identity.profileId))).catch(()=>{});});watchIdentity(async i=>{state.identity=i;if(!i?.profileId){message('Sign in to materialize your LCS profile icon in Global.');return;}message('Your LCS avatar is live.');await restorePosition();await loadWorldName();await flushPresence(true);watchPresence();});loadWorldName();
