import { db, fs, watchIdentity, profileById, safeText } from '/game/assets/js/eras-data.js';
const $=s=>document.querySelector(s);const state={identity:null,lobbies:[],friends:[],lobbyUnsub:null};
const say=(m,t='')=>{const e=$('#joinFeedback');if(!e)return;e.textContent=String(m).toUpperCase();e.dataset.tone=t;};
function lobbyHref(lobby){return lobby?.gameStyle==='galactic-dominion'?`/game/galactic-dominion/?lobby=${encodeURIComponent(lobby.id)}`:`/game/global/?lobby=${encodeURIComponent(lobby.id)}`;}
function modeLabel(lobby){return lobby?.gameStyle==='galactic-dominion'?'GALACTIC DOMINION':'TURN-BASED TACTICAL';}
function freshLobby(lobby){const ms=lobby.lastHeartbeatAt?.toMillis?.()||0;return lobby.status==='open'&&(!ms||Date.now()-ms<90000);}
async function joinLobby(lobby){if(!state.identity?.profileId){say('Sign in with Google first.','error');return;}try{const memberRef=fs.doc(db,'gameLobbies',lobby.id,'members',state.identity.profileId);const member=await fs.getDoc(memberRef);if(!member.exists()){const members=await fs.getDocs(fs.collection(db,'gameLobbies',lobby.id,'members'));if(members.size>=Number(lobby.maxPlayers||8)){say('That lobby is full.','error');return;}await fs.setDoc(memberRef,{profileId:state.identity.profileId,role:lobby.hostProfileId===state.identity.profileId?'host':'player',joinedAt:fs.serverTimestamp(),lastSeenAt:fs.serverTimestamp()});}location.href=lobbyHref(lobby);}catch(e){console.error(e);say(`Could not join lobby: ${e.code||e.message}`,'error');}}
function lobbyRow(lobby,host){const row=document.createElement('article');row.className='lobby-row';const copy=document.createElement('div');copy.innerHTML=`<strong>${safeText(lobby.name||'E.R.A.S. Game')}</strong><small>HOST ${safeText(host?.displayName||'Member')} // ${safeText(modeLabel(lobby))} // ${safeText(String(lobby.mapId||'global-plaza').toUpperCase())} // ${Number(lobby.maxPlayers||8)} MAX</small>`;const btn=document.createElement('button');btn.className='runtime-secondary';btn.type='button';btn.textContent='JOIN';btn.onclick=()=>joinLobby(lobby);row.append(copy,btn);return row;}
async function renderPublic(){const list=$('#publicList');list.innerHTML='';const publicLobbies=state.lobbies.filter(l=>freshLobby(l)&&l.visibility==='public');if(!publicLobbies.length){list.innerHTML='<p class="runtime-list-empty">NO PUBLIC LOBBIES ARE OPEN.</p>';return;}for(const lobby of publicLobbies){const host=await profileById(lobby.hostProfileId);list.appendChild(lobbyRow(lobby,host));}}
async function loadFriends(){const list=$('#friendList');if(!state.identity?.profileId){list.innerHTML='<p class="runtime-list-empty">SIGN IN TO LOAD FRIENDS.</p>';return;}try{const q=fs.query(fs.collection(db,'privateFriendships'),fs.where('members','array-contains',state.identity.profileId),fs.limit(100));const snap=await fs.getDocs(q);const ids=[];snap.forEach(d=>{for(const id of d.data().members||[])if(id!==state.identity.profileId&&!ids.includes(id))ids.push(id);});state.friends=ids;if(!ids.length){list.innerHTML='<p class="runtime-list-empty">NO LCS FRIENDSHIPS YET.</p>';return;}list.innerHTML='';for(const id of ids){const profile=await profileById(id);const open=state.lobbies.find(l=>freshLobby(l)&&l.hostProfileId===id&&['public','friends'].includes(l.visibility));const row=document.createElement('article');row.className='friend-row';const copy=document.createElement('div');copy.innerHTML=`<strong>${safeText(profile?.displayName||'Member')}</strong><small>${open?`HOSTING ${safeText(open.name||'E.R.A.S. Game')} // ${safeText(modeLabel(open))}`:'NO OPEN FRIEND LOBBY'}</small>`;const btn=document.createElement('button');btn.className='runtime-secondary';btn.type='button';btn.textContent=open?'JOIN':'OFFLINE';btn.disabled=!open;if(open)btn.onclick=()=>joinLobby(open);row.append(copy,btn);list.appendChild(row);}}catch(e){console.error(e);list.innerHTML='<p class="runtime-list-empty">FRIENDS COULD NOT BE LOADED.</p>';}}
function watchLobbies(){state.lobbyUnsub?.();const openQ=fs.query(fs.collection(db,'gameLobbies'),fs.where('status','==','open'));state.lobbyUnsub=fs.onSnapshot(openQ,snap=>{state.lobbies=snap.docs.map(d=>({id:d.id,...d.data()}));renderPublic();loadFriends();},e=>{console.error(e);$('#publicList').innerHTML='<p class="runtime-list-empty">LOBBIES COULD NOT BE LOADED.</p>';});}
document.querySelectorAll('[data-tab]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('is-active',b===btn));document.querySelectorAll('[data-panel]').forEach(p=>p.hidden=p.dataset.panel!==btn.dataset.tab);}));
$('#joinCode').addEventListener('input',e=>e.target.value=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6));
$('#codeForm').addEventListener('submit',async e=>{e.preventDefault();if(!state.identity?.profileId){say('Sign in with Google first.','error');return;}const code=$('#joinCode').value.trim().toUpperCase();const lobby=state.lobbies.find(l=>freshLobby(l)&&String(l.code||'').toUpperCase()===code);if(!lobby){say('No open lobby matches that code.','error');return;}await joinLobby(lobby);});
watchIdentity(i=>{state.identity=i;say(i?.profileId?'Ready to join a game.':'Sign in to join a lobby.',i?.profileId?'ok':'');loadFriends();});watchLobbies();
