import { db, fs, watchIdentity, safeText, avatarSvg } from '/game/assets/js/eras-data.js';
import { defaultHostedWorldSettings, settingsFromHostForm, DEFAULT_ICON_JSON, DEFAULT_SLIME_ICON_JSON } from '/game/config/world-settings.js?v=3.0.0';
import { HOSTED_GAME_MODES, VISIBILITY_OPTIONS, ACCESS_MODE_OPTIONS, hostedMode, hostedModeLabel, hostedModeRuntimeHref } from '/game/config/hosted-modes.js?v=1.0.0';
import { openOptionPicker, optionTriggerMarkup } from '/game/assets/js/hosted-option-picker.js?v=1.0.1';
import { createHostedOffer, deactivateHostedOffer } from '/game/assets/js/hosted-commerce.js?v=1.0.0';
import { assetPreviewUrl } from '/game/assets/js/catalog-assets.js?v=1.0.0';
import { getApp } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js';
import { getFunctions, httpsCallable } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-functions.js';

const $ = s => document.querySelector(s);
const state = { identity:null,lobby:null,heartbeat:null,content:defaultHostedWorldSettings(),holdings:[],holdingUnsub:null,catalog:{assets:[]},selectedHostAssets:[],bundles:[],offerIds:[],publishedGames:[],publishedUnsub:null };
const functions=getFunctions(getApp('site-account'));
const publishGameCall=httpsCallable(functions,'publishGame'), attachPublishedAccessOfferCall=httpsCallable(functions,'attachPublishedAccessOffer'), pausePublishedGameCall=httpsCallable(functions,'pausePublishedGame'), restorePublishedGameCall=httpsCallable(functions,'restorePublishedGame');
const say=(message,tone='')=>{const el=$('#hostFeedback');if(!el)return;el.textContent=String(message).toUpperCase();el.dataset.tone=tone;};
const esc=safeText;
const jsonPretty=value=>{try{return JSON.stringify(typeof value==='string'?JSON.parse(value):value,null,2);}catch(_){return String(value||'');}};
const slug=value=>String(value||'').toLowerCase().trim().replace(/[^a-z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,48);
const currentMode=()=>hostedMode($('#gameStyle')?.value);
const clamp=(v,min,max,fallback=min)=>{let n=Number(v);if(!Number.isFinite(n))n=fallback;return Math.max(min,Math.min(max,Math.floor(n)));};
function lobbyHref(lobby){return hostedModeRuntimeHref(lobby,location.pathname.startsWith('/game-mobile/'));}
function modeOptionList(){return Object.values(HOSTED_GAME_MODES).map(mode=>{const asset=catalogMeta(mode.assetId||'');return {...mode,image:mode.assetId?assetPreviewUrl(asset):undefined};});}
function currentModeOption(){return modeOptionList().find(option=>option.id===currentMode().id)||currentMode();}
function accessOption(id){return ACCESS_MODE_OPTIONS.find(o=>o.id===id)||ACCESS_MODE_OPTIONS[0];}
function visibilityOption(id){return VISIBILITY_OPTIONS.find(o=>o.id===id)||VISIBILITY_OPTIONS[0];}
function catalogMeta(assetId=''){return state.catalog.assets.find(a=>a.id===assetId)||{name:assetId||'Asset',thumbnail:'/public-assets/textures/slime_monochrome.png',source:'/public-assets/textures/slime_monochrome.png'};}
async function loadCatalog(){try{const r=await fetch('/public-assets/catalog.json',{cache:'no-store'});if(r.ok)state.catalog=await r.json();}catch(_){}}
function updatePickerButtons(){
  const gm=$('#gameModePicker');if(gm)gm.innerHTML=optionTriggerMarkup(currentModeOption(),'SELECT GAME MODE');
  const vis=$('#visibilityPicker');if(vis)vis.innerHTML=optionTriggerMarkup(visibilityOption($('#visibility')?.value),'SELECT VISIBILITY');
  const access=$('#accessModelPicker');if(access)access.innerHTML=optionTriggerMarkup(accessOption($('#accessModel')?.value),'SELECT ACCESS MODEL');
  const assetAccess=$('#assetAccessModelPicker');if(assetAccess)assetAccess.innerHTML=optionTriggerMarkup(accessOption($('#assetAccessModel')?.value),'SELECT ASSET LICENSE');
}
let lastAppliedModeId=$('#gameStyle')?.value||'arcade-topdown';
function setMode(id){if(!HOSTED_GAME_MODES[id])return;$('#gameStyle').value=id;applyModeUI();}
function setVisibility(id){if(!VISIBILITY_OPTIONS.some(o=>o.id===id))return;$('#visibility').value=id;updatePickerButtons();}
function setAccessModel(id,target='access'){
  if(!ACCESS_MODE_OPTIONS.some(o=>o.id===id))return;
  const assetTarget=target==='asset';
  const prefix=assetTarget?'asset':'access';
  const modelField=$(assetTarget?'#assetAccessModel':'#accessModel');
  if(!modelField)return;
  modelField.value=id;updatePickerButtons();
  const price=$(`#${prefix}PriceFields`);if(price)price.hidden=id==='free';
  document.querySelectorAll(`[data-${prefix}-quantity]`).forEach(el=>el.hidden=el.getAttribute(`data-${prefix}-quantity`)!==id);
}
function applyModeUI(){
  const mode=currentMode(), tactical=mode.id==='arcade-topdown', previousModeId=lastAppliedModeId;
  document.querySelectorAll('[data-tactical-only]').forEach(n=>n.hidden=!tactical);
  document.querySelectorAll('[data-mode-panel]').forEach(n=>n.hidden=n.dataset.modePanel!==mode.id);
  const map=$('#mapField');if(map)map.hidden=!tactical;
  const max=$('#maxPlayers');if(max){[...max.options].forEach(o=>o.disabled=Number(o.value)>mode.maxPlayers);if(Number(max.value)>mode.maxPlayers)max.value=String(mode.maxPlayers);}
  const currencyName=$('#worldCurrencyName'), currencySymbol=$('#worldCurrencySymbol'), startingBalance=$('#worldCurrencyStartingBalance'), deathLoss=$('#worldCurrencyDeathLossCap');
  const genericCurrency=currencyName?.value==='TOKENS'&&currencySymbol?.value==='◆'&&Number(startingBalance?.value)===0&&Number(deathLoss?.value)===10;
  const galacticCurrency=currencyName?.value==='GALACTIC CREDITS'&&currencySymbol?.value==='✦'&&Number(startingBalance?.value)===1500&&Number(deathLoss?.value)===0;
  if(mode.id==='galactic-dominion'&&previousModeId!=='galactic-dominion'&&genericCurrency){currencyName.value='GALACTIC CREDITS';currencySymbol.value='✦';startingBalance.value='1500';deathLoss.value='0';}
  else if(mode.id!=='galactic-dominion'&&previousModeId==='galactic-dominion'&&galacticCurrency){currencyName.value='TOKENS';currencySymbol.value='◆';startingBalance.value='0';deathLoss.value='10';}
  const button=$('#createLobby');if(button)button.textContent=`CREATE ${mode.name.toUpperCase()}`;
  lastAppliedModeId=mode.id;
  updatePickerButtons();
  if(state.identity?.profileId)say(`Ready to create ${mode.name}.`,'ok');
}
function holdingOption(h){const m=catalogMeta(h.assetId);return{id:h.id,name:m.name,description:`${h.assetId} // TINT ${h.tint||'#ffffff'}`,image:assetPreviewUrl(m),tags:['OWNED','HOST ASSET']};}
function renderHostAssets(){const root=$('#hostAssetSummary');if(!root)return;const selected=state.holdings.filter(h=>state.selectedHostAssets.includes(h.id));$('#assetLicenseControls').hidden=!selected.length;if(!selected.length){root.innerHTML='<p class="runtime-config-note">NO HOST ASSETS SELECTED.</p>';return;}root.innerHTML=selected.map(h=>{const m=catalogMeta(h.assetId);return `<div class="host-asset-chip" style="--asset-tint:${esc(h.tint||'#ffffff')}"><img src="${esc(assetPreviewUrl(m))}" alt=""><span><b>${esc(m.name)}</b><small>${esc(h.assetId)} // ${esc(h.tint||'#ffffff')}</small></span><span>VERIFIED OWNED</span></div>`;}).join('');}
function chooseHostAssets(){openOptionPicker({title:'Select host assets',options:state.holdings.map(holdingOption),selected:state.selectedHostAssets,multi:true,max:8,onSelect:ids=>{state.selectedHostAssets=ids;renderHostAssets();renderBundles();}});}
function hostAssetSnapshots(){return state.selectedHostAssets.map(id=>state.holdings.find(h=>h.id===id)).filter(Boolean).map(h=>({holdingId:h.id,assetId:h.assetId,tint:h.tint||'#ffffff'}));}
function watchHoldings(){state.holdingUnsub?.();state.holdings=[];state.selectedHostAssets=[];renderHostAssets();if(!state.identity?.profileId)return;const q=fs.query(fs.collection(db,'assetHoldings'),fs.where('ownerProfileId','==',state.identity.profileId),fs.limit(200));state.holdingUnsub=fs.onSnapshot(q,s=>{state.holdings=s.docs.map(d=>({id:d.id,...d.data()}));state.selectedHostAssets=state.selectedHostAssets.filter(id=>state.holdings.some(h=>h.id===id));renderHostAssets();renderBundles();},e=>console.error('Host assets',e));}
function newBundle(){return{id:crypto.randomUUID(),name:`${currentMode().name} Bundle`,price:25,plays:0,lives:0,minutes:0,permanent:false,assetIds:[...state.selectedHostAssets].slice(0,4)};}
function syncBundleInputs(){document.querySelectorAll('[data-bundle-id]').forEach(card=>{const b=state.bundles.find(x=>x.id===card.dataset.bundleId);if(!b)return;b.name=card.querySelector('[data-bundle-name]')?.value.trim().slice(0,60)||'Hosted Bundle';b.price=clamp(card.querySelector('[data-bundle-price]')?.value,1,1000000,25);b.plays=clamp(card.querySelector('[data-bundle-plays]')?.value,0,9999,0);b.lives=clamp(card.querySelector('[data-bundle-lives]')?.value,0,9999,0);b.minutes=clamp(card.querySelector('[data-bundle-minutes]')?.value,0,100000,0);b.permanent=!!card.querySelector('[data-bundle-permanent]')?.checked;});}
function renderBundles(){const root=$('#hostBundleList');if(!root)return;if(!state.bundles.length){root.innerHTML='<p class="runtime-config-note">NO HOST BUNDLES CONFIGURED.</p>';return;}root.innerHTML=state.bundles.map(b=>{const assets=b.assetIds.map(id=>state.holdings.find(h=>h.id===id)).filter(Boolean);return `<article class="host-bundle-card" data-bundle-id="${esc(b.id)}"><header><b>BUNDLE</b><button type="button" data-remove-bundle="${esc(b.id)}">REMOVE</button></header><div class="host-bundle-grid"><label class="runtime-field"><span>NAME</span><input data-bundle-name maxlength="60" value="${esc(b.name)}"></label><label class="runtime-field"><span>PRICE</span><input data-bundle-price type="number" min="1" max="1000000" value="${b.price}"></label><label class="runtime-field"><span>PLAYS</span><input data-bundle-plays type="number" min="0" max="9999" value="${b.plays}"></label><label class="runtime-field"><span>LIVES</span><input data-bundle-lives type="number" min="0" max="9999" value="${b.lives}"></label><label class="runtime-field"><span>MINUTES</span><input data-bundle-minutes type="number" min="0" max="100000" value="${b.minutes}"></label><label class="runtime-field"><span>PERMANENT ACCESS</span><input data-bundle-permanent type="checkbox" ${b.permanent?'checked':''}></label><button class="runtime-secondary" type="button" data-bundle-assets="${esc(b.id)}">SELECT ICONS</button></div><div class="host-bundle-assets">${assets.length?assets.map(h=>esc(catalogMeta(h.assetId).name)).join(' // '):'NO ICON LICENSES IN THIS BUNDLE'}</div></article>`;}).join('');}
function chooseBundleAssets(id){syncBundleInputs();const b=state.bundles.find(x=>x.id===id);if(!b)return;const allowed=state.holdings.filter(h=>state.selectedHostAssets.includes(h.id));openOptionPicker({title:'Bundle icon licenses',options:allowed.map(holdingOption),selected:b.assetIds,multi:true,max:4,onSelect:ids=>{b.assetIds=ids;renderBundles();}});}
function code(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let out='';for(let i=0;i<6;i++)out+=chars[Math.floor(Math.random()*chars.length)];return out;}
function parseIcon(raw){ const text = String(raw || '').trim(); const parsed = JSON.parse(text); if (!parsed || parsed.version !== 1 || !Array.isArray(parsed.layers) || !parsed.layers.length) throw new Error('Icon JSON must use the LCS version 1 layer format.'); return JSON.stringify(parsed); }
function areaOptions(selected=''){ return state.content.areas.map(a => `<option value="${esc(a.id)}" ${a.id===selected?'selected':''}>${esc(a.name)}</option>`).join(''); }
function itemOptions(selected=''){ return state.content.items.map(i => `<option value="${esc(i.id)}" ${i.id===selected?'selected':''}>${esc(i.name)}</option>`).join(''); }
function iconPreview(iconJson, name){ try { return avatarSvg({ displayName:name || 'ICON', avatarJson:iconJson }); } catch (_) { return avatarSvg({ displayName:'?', avatarJson:DEFAULT_ICON_JSON }); } }

function renderAreas(){ const root=$('#areaDefinitions'); if(!root)return; root.innerHTML=state.content.areas.map((a,i)=>`<article class="creator-definition" data-area-index="${i}"><header><b>${esc(a.name)}</b><button type="button" data-remove-area="${i}">REMOVE</button></header><div class="runtime-split"><label class="runtime-field"><span>AREA ID</span><input data-area="id" value="${esc(a.id)}"></label><label class="runtime-field"><span>AREA NAME</span><input data-area="name" value="${esc(a.name)}"></label></div><div class="creator-quad"><label class="runtime-field"><span>MIN X</span><input type="number" step="0.1" data-area="minX" value="${a.minX}"></label><label class="runtime-field"><span>MAX X</span><input type="number" step="0.1" data-area="maxX" value="${a.maxX}"></label><label class="runtime-field"><span>MIN Y</span><input type="number" step="0.1" data-area="minY" value="${a.minY}"></label><label class="runtime-field"><span>MAX Y</span><input type="number" step="0.1" data-area="maxY" value="${a.maxY}"></label></div></article>`).join(''); }
function renderItems(){ const root=$('#itemDefinitions'); if(!root)return; root.innerHTML=state.content.items.map((item,i)=>`<article class="creator-definition" data-item-index="${i}"><header><span class="creator-icon-preview">${iconPreview(item.iconJson,item.name)}</span><b>${esc(item.name)}</b><button type="button" data-remove-item="${i}">REMOVE</button></header><div class="runtime-split"><label class="runtime-field"><span>ITEM ID</span><input data-item="id" value="${esc(item.id)}"></label><label class="runtime-field"><span>NAME</span><input data-item="name" value="${esc(item.name)}"></label></div><div class="runtime-split"><label class="runtime-field"><span>TYPE</span><select data-item="kind"><option value="material" ${item.kind==='material'?'selected':''}>MATERIAL</option><option value="consumable" ${item.kind==='consumable'?'selected':''}>POTION / CONSUMABLE</option><option value="equipment" ${item.kind==='equipment'?'selected':''}>EQUIPMENT</option></select></label><label class="runtime-field"><span>EQUIPMENT SLOT</span><select data-item="equipmentSlot"><option value="">NONE</option><option value="weapon" ${item.equipmentSlot==='weapon'?'selected':''}>WEAPON</option></select></label></div><label class="runtime-field"><span>DESCRIPTION</span><input data-item="description" value="${esc(item.description)}"></label><div class="creator-quad"><label class="runtime-field"><span>HEAL HP</span><input type="number" min="0" max="50" data-item="healAmount" value="${item.healAmount||0}"></label><label class="runtime-field"><span>DMG MIN</span><input type="number" min="0" max="99" data-item="damageMin" value="${item.damageMin||0}"></label><label class="runtime-field"><span>DMG MAX</span><input type="number" min="0" max="99" data-item="damageMax" value="${item.damageMax||0}"></label><span></span></div><label class="runtime-field"><span>LCS JSON ICON // ONE ICON PER ITEM</span><textarea data-item="iconJson" class="creator-json">${esc(jsonPretty(item.iconJson))}</textarea></label></article>`).join(''); }
function renderMobs(){
  const root=$('#mobDefinitions'); if(!root)return;
  root.innerHTML=state.content.mobs.map((mob,i)=>{
    const drops=(mob.drops||[]).map((drop,di)=>`<div class="creator-inline-row" data-drop-index="${di}"><label class="runtime-field"><span>ITEM</span><select data-drop="itemId">${itemOptions(drop.itemId)}</select></label><label class="runtime-field"><span>DROP %</span><input type="number" min="0" max="100" step="0.1" data-drop="chancePct" value="${Math.round(Number(drop.chance||0)*100000)/1000}"></label><label class="runtime-field"><span>QTY</span><input type="number" min="1" max="99" data-drop="quantity" value="${Math.max(1,Number(drop.quantity||1))}"></label><button type="button" class="creator-row-remove" data-remove-drop="${di}">REMOVE</button></div>`).join('');
    return `<article class="creator-definition" data-mob-index="${i}"><header><span class="creator-icon-preview">${iconPreview(mob.iconJson,mob.name)}</span><b>${esc(mob.name)}</b><button type="button" data-remove-mob="${i}">REMOVE</button></header><div class="runtime-split"><label class="runtime-field"><span>MOB ID</span><input data-mob="id" value="${esc(mob.id)}"></label><label class="runtime-field"><span>NAME</span><input data-mob="name" value="${esc(mob.name)}"></label></div><div class="creator-quad"><label class="runtime-field"><span>HP</span><input type="number" min="1" max="100" data-mob="maxHp" value="${mob.maxHp}"></label><label class="runtime-field"><span>DAMAGE</span><input type="number" min="0" max="50" data-mob="damage" value="${mob.damage}"></label><label class="runtime-field"><span>ATTACK RANGE</span><input type="number" min="1" max="40" step="0.5" data-mob="attackRange" value="${mob.attackRange}"></label><label class="runtime-field"><span>SPAWN COUNT</span><input type="number" min="0" max="24" data-mob="spawnCount" value="${mob.spawnCount}"></label></div><div class="runtime-split"><label class="runtime-field"><span>SPAWN AREA</span><select data-mob="areaId">${areaOptions(mob.areaId)}</select><small>Spawn count above applies to this named area.</small></label><label class="runtime-field"><span>RESPAWN TURNS</span><input type="number" min="1" max="30" data-mob="respawnTurns" value="${mob.respawnTurns}"></label></div><label class="runtime-field"><span>LOCAL CURRENCY / KILL</span><input type="number" min="0" max="10000" data-mob="killReward" value="${mob.killReward||0}"></label><section class="creator-subsection"><div class="creator-section-head"><div><b>DROP TABLE</b><small>Independent chance per item. Custom-world drops never enter Global inventory.</small></div><button type="button" data-add-drop="${i}">+ DROP</button></div><div class="creator-inline-list">${drops||'<div class="runtime-list-empty">NO ITEM DROPS</div>'}</div></section><label class="runtime-field"><span>LCS JSON ICON // ONE ICON PER MOB</span><textarea data-mob="iconJson" class="creator-json">${esc(jsonPretty(mob.iconJson))}</textarea></label></article>`;
  }).join('');
}
function renderTerminals(){
  const root=$('#terminalDefinitions'); if(!root)return;
  root.innerHTML=state.content.terminals.map((t,i)=>{
    const offers=(t.offers||[]).map((offer,oi)=>`<div class="creator-inline-row" data-offer-index="${oi}"><label class="runtime-field"><span>DIRECTION</span><select data-offer="direction"><option value="buy" ${offer.direction==='buy'?'selected':''}>BUY</option><option value="sell" ${offer.direction==='sell'?'selected':''}>SELL</option></select></label><label class="runtime-field"><span>ITEM</span><select data-offer="itemId">${itemOptions(offer.itemId)}</select></label><label class="runtime-field"><span>PRICE</span><input type="number" min="1" max="100000" data-offer="price" value="${Math.max(1,Number(offer.price||1))}"></label><button type="button" class="creator-row-remove" data-remove-offer="${oi}">REMOVE</button></div>`).join('');
    return `<article class="creator-definition" data-terminal-index="${i}"><header><b>${esc(t.name)}</b><button type="button" data-remove-terminal="${i}">REMOVE</button></header><div class="runtime-split"><label class="runtime-field"><span>TACTICAL TARGET ID</span><input data-terminal="id" value="${esc(t.id)}"><small>Must match an interactable terminal object on the chosen map.</small></label><label class="runtime-field"><span>NAME</span><input data-terminal="name" value="${esc(t.name)}"></label></div><label class="runtime-field"><span>SUBTITLE</span><input data-terminal="subtitle" value="${esc(t.subtitle||'WORLD TERMINAL')}"></label><section class="creator-subsection"><div class="creator-section-head"><div><b>SHOP OFFERS</b><small>Uses this world's local currency only.</small></div><button type="button" data-add-offer="${i}">+ OFFER</button></div><div class="creator-inline-list">${offers||'<div class="runtime-list-empty">NO SHOP OFFERS</div>'}</div></section></article>`;
  }).join('');
}
function renderContent(){ renderAreas(); renderItems(); renderMobs(); renderTerminals(); }

function syncFromDom(){
  const previousAreaIds=state.content.areas.map(a=>a.id), previousItemIds=state.content.items.map(i=>i.id);
  document.querySelectorAll('[data-area-index]').forEach(card=>{const a=state.content.areas[Number(card.dataset.areaIndex)];card.querySelectorAll('[data-area]').forEach(input=>a[input.dataset.area]=input.type==='number'?Number(input.value):input.value);a.id=slug(a.id)||'area';});
  document.querySelectorAll('[data-item-index]').forEach(card=>{const item=state.content.items[Number(card.dataset.itemIndex)];card.querySelectorAll('[data-item]').forEach(input=>{const key=input.dataset.item;if(key==='iconJson') item[key]=parseIcon(input.value); else item[key]=input.type==='number'?Number(input.value):input.value;});item.id=slug(item.id)||'item';});
  const areaIdMap=new Map(previousAreaIds.map((id,i)=>[id,state.content.areas[i]?.id||id]));
  const itemIdMap=new Map(previousItemIds.map((id,i)=>[id,state.content.items[i]?.id||id]));
  document.querySelectorAll('[data-mob-index]').forEach(card=>{
    const mob=state.content.mobs[Number(card.dataset.mobIndex)];
    card.querySelectorAll('[data-mob]').forEach(input=>{const key=input.dataset.mob;if(key==='iconJson')mob[key]=parseIcon(input.value);else mob[key]=input.type==='number'?Number(input.value):input.value;});
    mob.id=slug(mob.id)||'mob'; mob.areaId=areaIdMap.get(mob.areaId)||mob.areaId; mob.drops=[];
    card.querySelectorAll('[data-drop-index]').forEach(row=>{const d={itemId:'',chance:0,quantity:1};row.querySelectorAll('[data-drop]').forEach(input=>{const key=input.dataset.drop;if(key==='chancePct')d.chance=Math.max(0,Math.min(100,Number(input.value)||0))/100;else d[key]=input.type==='number'?Number(input.value):input.value;});d.itemId=itemIdMap.get(d.itemId)||d.itemId;if(d.itemId)mob.drops.push(d);});
  });
  document.querySelectorAll('[data-terminal-index]').forEach(card=>{
    const t=state.content.terminals[Number(card.dataset.terminalIndex)];
    card.querySelectorAll('[data-terminal]').forEach(input=>t[input.dataset.terminal]=input.value); t.id=slug(t.id)||'terminal'; t.offers=[];
    card.querySelectorAll('[data-offer-index]').forEach((row,oi)=>{const o={id:`offer-${oi+1}`,direction:'buy',itemId:'',price:1};row.querySelectorAll('[data-offer]').forEach(input=>o[input.dataset.offer]=input.type==='number'?Number(input.value):input.value);o.itemId=itemIdMap.get(o.itemId)||o.itemId;o.id=slug(`${o.direction}-${o.itemId}-${oi+1}`);if(o.itemId)t.offers.push(o);});
  });
}

function settingsSummary(s,modeId){const m=hostedMode(modeId);if(modeId==='galactic-dominion')return `${m.name.toUpperCase()} // ${s.currency.startingBalance} ${esc(s.currency.name)} // ${s.galactic?.maxRounds||50} ROUNDS`;if(modeId==='arcade-topdown')return `HP ${s.player.maxHp} // ENERGY ${s.player.energyPerTurn} // MOVE ${s.player.maxWalkDistance} // ${s.mobs.length} MOB TYPES`;return `${m.name.toUpperCase()} // CUSTOM HOST RULES`;}
function render(){const box=$('#lobbyStatus');if(!box)return;if(!state.lobby){box.innerHTML='<div class="runtime-list-empty">NO ACTIVE LOBBY.</div>';return;}const l=state.lobby;box.innerHTML=`<div class="runtime-status-row"><span>LOBBY</span><b>${esc(l.name)}</b></div><div class="runtime-status-row"><span>MODE</span><b>${esc(hostedModeLabel(l.gameStyle))}</b></div><div class="runtime-status-row"><span>JOIN CODE</span><b class="lobby-code">${esc(l.code)}</b></div><div class="runtime-status-row"><span>WORLD RULES</span><b>${settingsSummary(l.settings,l.gameStyle)}</b></div><div class="runtime-status-row"><span>HOST ASSETS</span><b>${Number(l.hostAssets?.length||0)}</b></div><div class="runtime-status-row"><span>ACCESS</span><b>${l.accessOfferId?'PAID / CREDIT OFFER ACTIVE':'FREE'}</b></div><div class="runtime-actions"><a class="runtime-primary" style="display:grid;place-items:center;text-decoration:none;flex:1" href="${lobbyHref(l)}">ENTER GAME</a><button id="closeLobby" class="runtime-secondary runtime-danger" type="button">CLOSE LOBBY</button></div>`;$('#closeLobby').onclick=closeLobby;}
function publishedStatusLabel(game){return game.status==='timed_out'?'TIMED-OUT':game.status==='published'?'PUBLISHED':'PAUSED';}
function renderPublishedGames(){const root=$('#publishedGameList');if(!root)return;if(!state.identity?.profileId){root.innerHTML='<p class="runtime-list-empty">SIGN IN TO MANAGE PUBLISHED GAMES.</p>';return;}if(!state.publishedGames.length){root.innerHTML='<p class="runtime-list-empty">NO PUBLISHED GAMES YET.</p>';return;}root.innerHTML=state.publishedGames.slice().sort((a,b)=>(b.createdAt?.toMillis?.()||0)-(a.createdAt?.toMillis?.()||0)).map(g=>`<article class="published-game-row"><div><b>${esc(g.name||'E.R.A.S. Game')}</b><small>${esc(hostedModeLabel(g.gameStyle))} // ${esc(publishedStatusLabel(g))} // ${Number(g.totalMinutesBilled||0)} MIN BILLED</small></div><div class="published-game-actions">${g.status==='published'?`<a class="runtime-secondary" href="${esc(lobbyHref({id:g.lobbyId||g.id,gameStyle:g.gameStyle}))}">ENTER</a><button class="runtime-secondary" data-published-pause="${esc(g.id)}" type="button">PAUSE</button>`:`<button class="runtime-primary" data-published-restore="${esc(g.id)}" type="button">RESTORE PUBLISHING</button>`}</div></article>`).join('');}
function watchPublishedGames(){state.publishedUnsub?.();state.publishedGames=[];renderPublishedGames();if(!state.identity?.profileId)return;const q=fs.query(fs.collection(db,'publishedGames'),fs.where('ownerProfileId','==',state.identity.profileId),fs.limit(100));state.publishedUnsub=fs.onSnapshot(q,s=>{state.publishedGames=s.docs.map(d=>({id:d.id,...d.data()}));renderPublishedGames();},e=>{console.error('Published games',e);const root=$('#publishedGameList');if(root)root.innerHTML='<p class="runtime-list-empty">PUBLISHED GAMES COULD NOT BE LOADED.</p>';});}
async function publishGame(){if(!state.identity?.profileId)return say('Sign in with Google first.','error');const mode=currentMode();if(mode.id==='arcade-topdown'){try{syncFromDom();}catch(e){return say(e.message,'error');}}syncBundleInputs();const name=$('#lobbyName').value.trim().slice(0,50)||'E.R.A.S. Game',settings=settingsFromHostForm(document,state.content,mode.id),serialized=JSON.stringify(settings);if(serialized.length>700000)return say('World definition is too large.','error');const maxPlayers=Math.min(mode.maxPlayers,Number($('#maxPlayers').value)||8),mapId=mode.id==='arcade-topdown'?$('#mapId').value:mode.mapId,publishButton=$('#publishGame'),old=publishButton?.textContent||'PUBLISH GAME';if(publishButton){publishButton.disabled=true;publishButton.textContent='PUBLISHING…';}try{say('Publishing game // billing first minute…');const result=(await publishGameCall({name,visibility:$('#visibility').value,maxPlayers,mapId,gameStyle:mode.id,description:$('#description').value.trim().slice(0,240),settings,hostAssets:hostAssetSnapshots()})).data;if(!result?.ok)throw new Error('Publish service did not confirm the game.');const lobbyId=result.lobbyId,publishedGameId=result.publishedGameId;const offers=await createCommerceOffers(lobbyId,name);const access=offers.find(o=>o.offerType==='game_access');if(access)await attachPublishedAccessOfferCall({publishedGameId,accessOfferId:access.id});say(`${mode.name} published. 1 Credit/minute while published. It will time out instead of being deleted if Credits run out.`,'ok');}catch(e){console.error('Publish game',e);say(`Could not publish game: ${e?.message||e?.code||e}`,'error');}finally{if(publishButton){publishButton.disabled=false;publishButton.textContent=old;}}}
async function pausePublishedGame(id){try{await pausePublishedGameCall({publishedGameId:id});say('Published game paused. Stats and lobby data were retained.','ok');}catch(e){console.error(e);say(`Could not pause published game: ${e?.message||e?.code||e}`,'error');}}
async function restorePublishedGame(id){try{await restorePublishedGameCall({publishedGameId:id});say('Publishing restored. The first restored minute cost 1 Credit.','ok');}catch(e){console.error(e);say(`Could not restore published game: ${e?.message||e?.code||e}`,'error');}}
async function closeLobby(){if(!state.lobby||!state.identity)return;try{await fs.updateDoc(fs.doc(db,'gameLobbies',state.lobby.id),{status:'closed',updatedAt:fs.serverTimestamp(),lastHeartbeatAt:fs.serverTimestamp()});for(const id of state.offerIds)deactivateHostedOffer(id,state.identity.profileId).catch(()=>{});clearInterval(state.heartbeat);state.lobby=null;state.offerIds=[];render();say('Lobby closed.','ok');}catch(e){console.error(e);say(`Could not close lobby: ${e.code||e.message}`,'error');}}
function offerPayloadForModel(model,prefix){return{billing:model,playCount:model==='per_play'?clamp($(`#${prefix}PlayCount`)?.value,1,9999,1):0,lifeCount:model==='per_life'?clamp($(`#${prefix}LifeCount`)?.value,1,9999,1):0,minutes:model==='playtime'?clamp($(`#${prefix}Minutes`)?.value,1,100000,30):0,permanent:model==='permanent'};}
async function createCommerceOffers(lobbyId,lobbyName){const created=[];const model=$('#accessModel').value;if(model!=='free'){const o=await createHostedOffer({sellerProfileId:state.identity.profileId,lobbyId,offerType:'game_access',title:`${lobbyName} — Access`,description:`${currentMode().name} hosted-game access.`,priceCredits:clamp($('#accessPriceCredits').value,1,1000000,10),...offerPayloadForModel(model,'access')});created.push(o);}
  const assetModel=$('#assetAccessModel').value;if(assetModel!=='free'){for(const h of state.holdings.filter(x=>state.selectedHostAssets.includes(x.id))){const m=catalogMeta(h.assetId);const o=await createHostedOffer({sellerProfileId:state.identity.profileId,lobbyId,offerType:'icon_license',title:`${m.name} — Hosted Icon License`,description:`Use this host-owned icon in ${lobbyName}. Ownership remains with the seller.`,priceCredits:clamp($('#assetPriceCredits').value,1,1000000,5),assetHoldingIds:[h.id],...offerPayloadForModel(assetModel,'asset')});created.push(o);}}
  syncBundleInputs();for(const b of state.bundles){if(!(b.plays||b.lives||b.minutes||b.permanent||b.assetIds.length))continue;const o=await createHostedOffer({sellerProfileId:state.identity.profileId,lobbyId,offerType:'bundle',billing:'bundle',title:b.name,description:`Bundle for ${lobbyName}. Exact contents shown before purchase.`,priceCredits:b.price,playCount:b.plays,lifeCount:b.lives,minutes:b.minutes,permanent:b.permanent,assetHoldingIds:b.assetIds.slice(0,4)});created.push(o);}return created;}
async function createLobby(event){event.preventDefault();if(!state.identity?.profileId)return say('Sign in with Google first.','error');const mode=currentMode();if(mode.id==='arcade-topdown'){try{syncFromDom();}catch(e){return say(e.message,'error');}}syncBundleInputs();const id=crypto.randomUUID(),joinCode=code(),name=$('#lobbyName').value.trim().slice(0,50)||'E.R.A.S. Game';const settings=settingsFromHostForm(document,state.content,mode.id);const serialized=JSON.stringify(settings);if(serialized.length>700000)return say('World definition is too large.','error');const maxPlayers=Math.min(mode.maxPlayers,Number($('#maxPlayers').value)||8);const mapId=mode.id==='arcade-topdown'?$('#mapId').value:mode.mapId;const lobby={name,code:joinCode,hostProfileId:state.identity.profileId,visibility:$('#visibility').value,maxPlayers,mapId,gameStyle:mode.id,description:$('#description').value.trim().slice(0,240),settings,hostAssets:hostAssetSnapshots(),accessOfferId:'',status:'open',sourceType:'hosted',publishedGameId:'',createdAt:fs.serverTimestamp(),updatedAt:fs.serverTimestamp(),lastHeartbeatAt:fs.serverTimestamp()};let lobbyCreated=false;const createdOffers=[];try{say(`Creating ${mode.name}…`);await fs.setDoc(fs.doc(db,'gameLobbies',id),lobby);lobbyCreated=true;const offers=await createCommerceOffers(id,name);createdOffers.push(...offers);const access=offers.find(o=>o.offerType==='game_access');if(access){lobby.accessOfferId=access.id;await fs.updateDoc(fs.doc(db,'gameLobbies',id),{accessOfferId:access.id,updatedAt:fs.serverTimestamp()});}await fs.setDoc(fs.doc(db,'gameLobbies',id,'members',state.identity.profileId),{profileId:state.identity.profileId,role:'host',accessEntitlementId:'',accessStartedAt:fs.serverTimestamp(),accessLeaseSeconds:600,joinedAt:fs.serverTimestamp(),lastSeenAt:fs.serverTimestamp()});state.offerIds=offers.map(o=>o.id);state.lobby={id,...lobby,createdAt:null,updatedAt:null,lastHeartbeatAt:null};render();say(`${mode.name} created. ${offers.length} hosted commerce offer${offers.length===1?'':'s'} active.`,'ok');clearInterval(state.heartbeat);state.heartbeat=setInterval(()=>{if(state.lobby)fs.updateDoc(fs.doc(db,'gameLobbies',state.lobby.id),{lastHeartbeatAt:fs.serverTimestamp(),updatedAt:fs.serverTimestamp()}).catch(()=>{});},20000);}catch(e){console.error(e);for(const o of createdOffers)deactivateHostedOffer(o.id,state.identity.profileId).catch(()=>{});if(lobbyCreated){try{await fs.deleteDoc(fs.doc(db,'gameLobbies',id));}catch(_){}}say(e?.code==='permission-denied'?'Hosted game creation was blocked by Firestore rules. Publish the included firestore.rules and retry.':`Could not create lobby: ${e.code||e.message}`,'error');}}

$('#hostForm')?.addEventListener('submit',createLobby);
$('#publishGame')?.addEventListener('click',()=>publishGame().catch(console.error));
$('#gameModePicker')?.addEventListener('click',()=>openOptionPicker({title:'Select game mode',options:modeOptionList(),selected:currentMode().id,onSelect:setMode}));
$('#visibilityPicker')?.addEventListener('click',()=>openOptionPicker({title:'Select visibility',options:VISIBILITY_OPTIONS,selected:$('#visibility').value,onSelect:setVisibility}));
$('#accessModelPicker')?.addEventListener('click',()=>openOptionPicker({title:'Game access model',options:ACCESS_MODE_OPTIONS,selected:$('#accessModel').value,onSelect:id=>setAccessModel(id,'access')}));
$('#assetAccessModelPicker')?.addEventListener('click',()=>openOptionPicker({title:'Host asset license model',options:ACCESS_MODE_OPTIONS,selected:$('#assetAccessModel').value,onSelect:id=>setAccessModel(id,'asset')}));
$('#hostAssetPicker')?.addEventListener('click',chooseHostAssets);
$('#addHostBundle')?.addEventListener('click',()=>{syncBundleInputs();if(state.bundles.length>=6)return say('A hosted lobby can publish up to 6 bundles.','error');state.bundles.push(newBundle());renderBundles();});
$('#addArea')?.addEventListener('click',()=>{try{syncFromDom();}catch(e){return say(e.message,'error');}state.content.areas.push({id:`area-${state.content.areas.length+1}`,name:`AREA ${state.content.areas.length+1}`,minX:10,maxX:90,minY:10,maxY:90});renderContent();});
$('#addItem')?.addEventListener('click',()=>{try{syncFromDom();}catch(e){return say(e.message,'error');}state.content.items.push({id:`item-${state.content.items.length+1}`,name:`Item ${state.content.items.length+1}`,kind:'material',description:'',healAmount:0,equipmentSlot:'',damageMin:0,damageMax:0,iconJson:DEFAULT_ICON_JSON});renderContent();});
$('#addMob')?.addEventListener('click',()=>{try{syncFromDom();}catch(e){return say(e.message,'error');}state.content.mobs.push({id:`mob-${state.content.mobs.length+1}`,name:`Mob ${state.content.mobs.length+1}`,maxHp:1,damage:1,attackRange:13,areaId:state.content.areas[0]?.id||'cache-yard',spawnCount:1,respawnTurns:1,killReward:1,drops:[],iconJson:DEFAULT_SLIME_ICON_JSON});renderContent();});
$('#addTerminal')?.addEventListener('click',()=>{try{syncFromDom();}catch(e){return say(e.message,'error');}state.content.terminals.push({id:`terminal-${state.content.terminals.length+1}`,name:`TERMINAL ${state.content.terminals.length+1}`,subtitle:'WORLD TERMINAL',offers:[]});renderContent();});
document.addEventListener('click',e=>{const pause=e.target.closest('[data-published-pause]');if(pause){pausePublishedGame(pause.dataset.publishedPause);return;}const restore=e.target.closest('[data-published-restore]');if(restore){restorePublishedGame(restore.dataset.publishedRestore);return;}const bundleRemove=e.target.closest('[data-remove-bundle]');if(bundleRemove){syncBundleInputs();state.bundles=state.bundles.filter(b=>b.id!==bundleRemove.dataset.removeBundle);renderBundles();return;}const bundleAssets=e.target.closest('[data-bundle-assets]');if(bundleAssets){chooseBundleAssets(bundleAssets.dataset.bundleAssets);return;}const addDrop=e.target.closest('[data-add-drop]');if(addDrop){try{syncFromDom();}catch(err){return say(err.message,'error');}const mob=state.content.mobs[Number(addDrop.dataset.addDrop)],first=state.content.items[0]?.id||'';if(!first)return say('Create an item before adding a drop.','error');mob.drops.push({itemId:first,chance:.05,quantity:1});renderContent();return;}const removeDrop=e.target.closest('[data-remove-drop]');if(removeDrop){const card=removeDrop.closest('[data-mob-index]');try{syncFromDom();}catch(err){return say(err.message,'error');}state.content.mobs[Number(card.dataset.mobIndex)].drops.splice(Number(removeDrop.dataset.removeDrop),1);renderContent();return;}const addOffer=e.target.closest('[data-add-offer]');if(addOffer){try{syncFromDom();}catch(err){return say(err.message,'error');}const terminal=state.content.terminals[Number(addOffer.dataset.addOffer)],first=state.content.items[0]?.id||'';if(!first)return say('Create an item before adding a shop offer.','error');terminal.offers.push({id:`offer-${terminal.offers.length+1}`,direction:'buy',itemId:first,price:1});renderContent();return;}const removeOffer=e.target.closest('[data-remove-offer]');if(removeOffer){const card=removeOffer.closest('[data-terminal-index]');try{syncFromDom();}catch(err){return say(err.message,'error');}state.content.terminals[Number(card.dataset.terminalIndex)].offers.splice(Number(removeOffer.dataset.removeOffer),1);renderContent();return;}for(const kind of ['area','item','mob','terminal']){const node=e.target.closest(`[data-remove-${kind}]`);if(!node)continue;try{syncFromDom();}catch(err){return say(err.message,'error');}state.content[`${kind}s`].splice(Number(node.getAttribute(`data-remove-${kind}`)),1);renderContent();return;}});

await loadCatalog();renderContent();renderBundles();setAccessModel('free','access');setAccessModel('free','asset');applyModeUI();watchIdentity(identity=>{state.identity=identity;watchHoldings();watchPublishedGames();const button=$('#createLobby');if(button)button.disabled=!identity?.profileId;say(identity?.profileId?`Ready to create ${currentMode().name}.`:'Sign in to create a lobby.',identity?.profileId?'ok':'');});
