import { db, fs, watchIdentity, safeText, avatarSvg } from '/game/assets/js/eras-data.js';
import { hostedMode } from '/game/config/hosted-modes.js?v=1.4.0';
import { offersForLobby, purchaseHostedOffer, entitlementUsable } from '/game/assets/js/hosted-commerce.js?v=1.1.0';
import { obtainLobbyEntitlement, createLobbyMembership, maintainLobbyMembership } from '/game/assets/js/hosted-join-compat.js?v=1.1.0';
import { assetPreviewUrl, hydrateVariantPreviewImage } from '/game/assets/js/catalog-assets.js?v=1.1.0';
import { getApp } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js';
import { getFunctions, httpsCallable } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-functions.js';

const $=s=>document.querySelector(s), params=new URLSearchParams(location.search), isGlobalDash=location.pathname.startsWith('/game/global/escape-pod-dash'), lobbyId=params.get('lobby')||'';
const state={identity:null,lobby:null,mode:null,offers:[],entitlements:[],catalog:{assets:[]},selectedAssetId:'',score:0,status:'ready',game:null,raf:0,accessLeaseStop:null,podHoldings:[],selectedPodSkin:'standard',pilotImage:null,podBuying:false};
const esc=safeText, say=(m,t='')=>{const e=$('#gameFeedback');if(e){e.textContent=String(m).toUpperCase();e.dataset.tone=t;}};
const functions=getFunctions(getApp('site-account'));
const acquireAssetVariantCall=httpsCallable(functions,'acquireAssetVariant');
const setScore=v=>{state.score=Math.max(0,Math.floor(Number(v)||0));$('#runScore').textContent=state.score.toLocaleString();};
const meta=id=>state.catalog.assets.find(a=>a.id===id)||{name:id||'Asset',source:'/public-assets/textures/slime_monochrome.png',thumbnail:'/public-assets/textures/slime_monochrome.png'};
async function loadCatalog(){try{const r=await fetch('/public-assets/catalog.json',{cache:'no-store'});if(r.ok)state.catalog=await r.json();}catch(_){}}
const ESCAPE_POD_ASSET_ID='eras:mode_escape_pod_dash';
const ESCAPE_POD_SKINS=Object.freeze([
  Object.freeze({id:'standard',name:'STANDARD POD',price:0,storage:'mode|rule=highest_score',variant:{rule:'Highest Score'},body:'#9fe4e3',accent:'#d7fbff',glass:'#071b26',trail:'#79efff',style:'standard'}),
  Object.freeze({id:'comet',name:'COMET POD',price:1,storage:'mode|custom_rule=comet_pod',variant:{rule:'__custom__',customRule:'Comet Pod'},body:'#ff9b72',accent:'#ffe7a8',glass:'#25110d',trail:'#ffbf57',style:'comet'}),
  Object.freeze({id:'aurora',name:'AURORA POD',price:1,storage:'mode|custom_rule=aurora_pod',variant:{rule:'__custom__',customRule:'Aurora Pod'},body:'#8ce7c8',accent:'#bb96ff',glass:'#071b20',trail:'#8c7dff',style:'aurora'}),
  Object.freeze({id:'bulwark',name:'BULWARK POD',price:1,storage:'mode|custom_rule=bulwark_pod',variant:{rule:'__custom__',customRule:'Bulwark Pod'},body:'#9eaab4',accent:'#ffcd68',glass:'#10171c',trail:'#ffa845',style:'bulwark'}),
  Object.freeze({id:'nova',name:'NOVA POD',price:1,storage:'mode|custom_rule=nova_pod',variant:{rule:'__custom__',customRule:'Nova Pod'},body:'#e8e8f5',accent:'#ff74bd',glass:'#180b1b',trail:'#ff66da',style:'nova'})
]);
const podSkin=id=>ESCAPE_POD_SKINS.find(x=>x.id===id)||ESCAPE_POD_SKINS[0];
const podStorageKey=()=>`eras.escape-pod-dash.skin.${state.identity?.profileId||'guest'}`;
const podOwned=skin=>skin.price===0||state.podHoldings.some(h=>h.assetId===ESCAPE_POD_ASSET_ID&&h.tint===skin.storage&&h.archived!==true);
function pilotDataUrl(){try{return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(avatarSvg(state.identity?.profile||{}))}`;}catch(_){return '';}}
async function loadPilotImage(){const src=pilotDataUrl();if(!src){state.pilotImage=null;return;}const img=new Image();img.decoding='async';img.src=src;try{await img.decode();state.pilotImage=img;}catch(_){state.pilotImage=null;}}
async function loadPodHoldings(){state.podHoldings=[];if(!state.identity?.profileId)return;try{const q=fs.query(fs.collection(db,'assetHoldings'),fs.where('ownerProfileId','==',state.identity.profileId),fs.limit(200));const snap=await fs.getDocs(q);state.podHoldings=snap.docs.map(d=>({id:d.id,...d.data()})).filter(h=>h.assetId===ESCAPE_POD_ASSET_ID&&h.archived!==true);}catch(e){console.debug('Escape pod holdings',e?.code||e);}}
function podMiniMarkup(skin){const pilot=pilotDataUrl();return `<span class="pod-mini" style="--pod-body:${skin.body};--pod-accent:${skin.accent};--pod-glass:${skin.glass};--pod-trail:${skin.trail}"><i class="pod-mini-trail"></i><i class="pod-mini-shell"></i><i class="pod-mini-glass">${pilot?`<img src="${esc(pilot)}" alt="">`:''}</i></span>`;}
function renderPodPicker(){cancelAnimationFrame(state.raf);state.game=null;state.status='ready';setScore(0);const root=$('#gameStage'),selected=podSkin(state.selectedPodSkin);root.innerHTML=`<section class="pod-picker"><header><p>ESCAPE POD // COSMETIC LOADOUT</p><h2>CHOOSE YOUR POD</h2><small>YOUR E.R.A.S. ICON RIDES INSIDE THE COCKPIT. EVERY POD USES THE SAME HITBOX AND MOVEMENT.</small></header><div class="pod-skin-grid">${ESCAPE_POD_SKINS.map(skin=>{const owned=podOwned(skin),active=skin.id===selected.id;return `<article class="pod-skin-card ${active?'is-selected':''} ${owned?'is-owned':'is-locked'}" data-pod-card="${skin.id}">${podMiniMarkup(skin)}<div><b>${skin.name}</b><small>${owned?(skin.price===0?'DEFAULT POD':'OWNED POD SKIN'):`${skin.price} CREDIT`}</small></div><button type="button" ${state.podBuying?'disabled':''} ${owned?`data-pod-skin="${skin.id}"`:`data-buy-pod="${skin.id}"`}>${owned?(active?'SELECTED':'SELECT'):`BUY ${skin.price} CREDIT`}</button></article>`;}).join('')}</div><div class="pod-picker-actions"><button type="button" data-start-dash ${podOwned(selected)?'':'disabled'}>LAUNCH ${esc(selected.name)}</button><p>SWAP PODS BEFORE EVERY RUN // PURCHASED PODS REMAIN IN YOUR E.R.A.S. ASSET HOLDINGS.</p></div></section>`;hud(['9 POSITION GRID','3 × 3 MOVEMENT','GALAXY RUN']);$('#gameControls').innerHTML='';say('Choose a pod, then launch.','ok');}
async function prepareDash(){await Promise.all([loadPodHoldings(),loadPilotImage()]);let saved='';try{saved=localStorage.getItem(podStorageKey())||'';}catch(_){}if(saved&&podOwned(podSkin(saved)))state.selectedPodSkin=saved;else state.selectedPodSkin='standard';renderPodPicker();}
function choosePodSkin(id){const skin=podSkin(id);if(!podOwned(skin))return;state.selectedPodSkin=skin.id;try{localStorage.setItem(podStorageKey(),skin.id);}catch(_){}renderPodPicker();}
async function buyPodSkin(id){if(state.podBuying)return;const skin=podSkin(id);if(!state.identity?.profileId)return say('Sign in to buy pod skins.','error');if(podOwned(skin))return choosePodSkin(id);if(!confirm(`BUY ${skin.name}?\n\n${skin.price} E.R.A.S. CREDIT\n\nCOSMETIC ONLY // SAME HITBOX AND SPEED`))return;state.podBuying=true;renderPodPicker();try{say(`Purchasing ${skin.name}…`);const result=(await acquireAssetVariantCall({assetId:ESCAPE_POD_ASSET_ID,variant:skin.variant})).data;if(!result?.ok)throw new Error('Asset purchase was not confirmed.');await loadPodHoldings();state.selectedPodSkin=skin.id;try{localStorage.setItem(podStorageKey(),skin.id);}catch(_){}say(`${skin.name} added to your E.R.A.S. assets.`,'ok');}catch(e){console.error('Pod purchase',e);say(e?.message||e?.code||'Pod purchase failed.','error');}finally{state.podBuying=false;renderPodPicker();}}
function dashControls(){const cells=[['0','0','↖'],['0','1','↑'],['0','2','↗'],['1','0','←'],['1','1','●'],['1','2','→'],['2','0','↙'],['2','1','↓'],['2','2','↘']];$('#gameControls').innerHTML=`<div class="dash-grid-controls">${cells.map(([r,c,label])=>`<button type="button" data-game-action="pos-${r}-${c}" aria-label="Move pod to row ${Number(r)+1}, column ${Number(c)+1}">${label}</button>`).join('')}</div>`;}
function dashPoint(canvas,row,col){const xs=[.22,.5,.78],ys=[.34,.59,.82];return{x:canvas.width*xs[col],y:canvas.height*ys[row]};}
function dashStars(canvas,count=92){return Array.from({length:count},()=>({x:Math.random()*canvas.width,y:Math.random()*canvas.height,z:.25+Math.random()*1.5,size:.6+Math.random()*1.7}));}
const DASH_PATH_COLORS=Object.freeze(['#6ffcff','#8cff73','#ff6fd8','#ffd86f','#8b7dff','#ff785e','#6fa8ff','#eaff6f']);
function dashPathColor(){return DASH_PATH_COLORS[Math.floor(Math.random()*DASH_PATH_COLORS.length)];}
function drawGalaxy(ctx,g,dt){const c=g.canvas,vanish={x:c.width/2,y:c.height*.11};ctx.fillStyle='#02060d';ctx.fillRect(0,0,c.width,c.height);const halo=ctx.createRadialGradient(vanish.x,vanish.y,0,vanish.x,vanish.y,c.width*.65);halo.addColorStop(0,'rgba(92,78,180,.22)');halo.addColorStop(.35,'rgba(25,73,111,.10)');halo.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=halo;ctx.fillRect(0,0,c.width,c.height);for(const star of g.stars){star.y+=dt*(.018+g.speed*.002)*star.z;if(star.y>c.height+8){star.y=-5;star.x=Math.random()*c.width;}ctx.fillStyle=`rgba(215,235,255,${Math.min(.9,.3+star.z*.3)})`;ctx.fillRect(star.x,star.y,star.size*star.z,star.size*star.z);}ctx.strokeStyle='rgba(111,165,206,.10)';ctx.lineWidth=1;for(let r=0;r<3;r++)for(let col=0;col<3;col++){const p=dashPoint(c,r,col);ctx.beginPath();ctx.moveTo(vanish.x,vanish.y);ctx.lineTo(p.x,p.y);ctx.stroke();ctx.strokeStyle='rgba(111,165,206,.14)';ctx.strokeRect(p.x-34,p.y-22,68,44);ctx.strokeStyle='rgba(111,165,206,.10)';}
  // Each incoming hazard lights its own approach path with a persistent random neon color.
  for(const h of g.hazards||[]){if(h.z>=1.08)continue;const p=dashPoint(c,h.row,h.col),t=Math.max(0,Math.min(1,h.z)),color=h.pathColor||'#6ffcff';ctx.save();ctx.globalAlpha=.28+.5*t;ctx.strokeStyle=color;ctx.shadowColor=color;ctx.shadowBlur=14+24*t;ctx.lineWidth=1.8+2.2*t;ctx.beginPath();ctx.moveTo(vanish.x,vanish.y);ctx.lineTo(p.x,p.y);ctx.stroke();ctx.globalAlpha=.18+.35*t;ctx.lineWidth=1.2+1.5*t;ctx.strokeRect(p.x-34,p.y-22,68,44);ctx.restore();}
  ctx.fillStyle='rgba(91,63,163,.13)';ctx.beginPath();ctx.arc(c.width*.10,c.height*.18,44,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(168,130,255,.16)';ctx.beginPath();ctx.ellipse(c.width*.10,c.height*.18,68,16,-.22,0,Math.PI*2);ctx.stroke();}
function hazardPalette(type){if(type==='planet')return['#5b74bd','#8fc3d6'];if(type==='satellite')return['#9baab7','#e2c16e'];if(type==='flare')return['#e86955','#ffd277'];return['#6b5962','#b9867a'];}
function drawHazard(ctx,g,h){const c=g.canvas,p=dashPoint(c,h.row,h.col),vanish={x:c.width/2,y:c.height*.11},t=Math.max(0,Math.min(1,h.z)),x=vanish.x+(p.x-vanish.x)*t,y=vanish.y+(p.y-vanish.y)*t,size=8+44*t*t,[a,b]=hazardPalette(h.type);ctx.save();ctx.translate(x,y);ctx.rotate(h.spin+t*2.4);if(h.type==='satellite'){ctx.fillStyle=a;ctx.fillRect(-size*.18,-size*.18,size*.36,size*.36);ctx.fillStyle=b;ctx.fillRect(-size*.7,-size*.1,size*.45,size*.2);ctx.fillRect(size*.25,-size*.1,size*.45,size*.2);}else if(h.type==='flare'){const grd=ctx.createRadialGradient(0,0,0,0,0,size);grd.addColorStop(0,b);grd.addColorStop(.45,a);grd.addColorStop(1,'rgba(232,105,85,0)');ctx.fillStyle=grd;ctx.beginPath();ctx.arc(0,0,size,0,Math.PI*2);ctx.fill();}else{ctx.fillStyle=a;ctx.beginPath();ctx.arc(0,0,size,0,Math.PI*2);ctx.fill();ctx.fillStyle=b;ctx.globalAlpha=.45;ctx.beginPath();ctx.arc(-size*.25,-size*.25,size*.22,0,Math.PI*2);ctx.fill();if(h.type==='planet'){ctx.globalAlpha=.5;ctx.strokeStyle=b;ctx.lineWidth=Math.max(1,size*.08);ctx.beginPath();ctx.ellipse(0,0,size*1.35,size*.32,.28,0,Math.PI*2);ctx.stroke();}}ctx.restore();}
function drawEscapePod(ctx,g){const c=g.canvas,p=dashPoint(c,g.row,g.col),skin=podSkin(g.skinId),scale=.82+g.row*.10,bank=(g.bank||0)*.10;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(bank);ctx.scale(scale,scale);const trail=ctx.createLinearGradient(0,28,0,95);trail.addColorStop(0,skin.trail);trail.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=trail;ctx.beginPath();ctx.moveTo(-15,25);ctx.lineTo(-4,92);ctx.lineTo(4,92);ctx.lineTo(15,25);ctx.closePath();ctx.fill();ctx.shadowColor=skin.trail;ctx.shadowBlur=18;ctx.fillStyle=skin.body;ctx.strokeStyle=skin.accent;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(0,-46);ctx.bezierCurveTo(34,-33,38,5,24,35);ctx.bezierCurveTo(10,49,-10,49,-24,35);ctx.bezierCurveTo(-38,5,-34,-33,0,-46);ctx.closePath();ctx.fill();ctx.stroke();ctx.shadowBlur=0;if(skin.style==='comet'){ctx.fillStyle=skin.accent;ctx.beginPath();ctx.moveTo(-27,10);ctx.lineTo(-52,28);ctx.lineTo(-22,25);ctx.fill();ctx.beginPath();ctx.moveTo(27,10);ctx.lineTo(52,28);ctx.lineTo(22,25);ctx.fill();}else if(skin.style==='bulwark'){ctx.strokeStyle=skin.accent;ctx.lineWidth=5;ctx.strokeRect(-31,-4,62,28);}else if(skin.style==='aurora'){ctx.strokeStyle=skin.accent;ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,2,35,Math.PI*.15,Math.PI*.85);ctx.stroke();}else if(skin.style==='nova'){ctx.fillStyle=skin.accent;for(const x of [-30,30]){ctx.beginPath();ctx.arc(x,14,5,0,Math.PI*2);ctx.fill();}}ctx.fillStyle=skin.glass;ctx.strokeStyle=skin.accent;ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(0,-10,20,17,0,0,Math.PI*2);ctx.fill();ctx.stroke();if(state.pilotImage){ctx.save();ctx.beginPath();ctx.ellipse(0,-10,16,13,0,0,Math.PI*2);ctx.clip();ctx.drawImage(state.pilotImage,-15,-25,30,30);ctx.restore();}ctx.fillStyle=skin.accent;ctx.fillRect(-18,34,11,7);ctx.fillRect(7,34,11,7);ctx.restore();}
function finishDash(message,tone='error'){const g=state.game;if(!g||g.type!=='dash')return;state.status='finished';cancelAnimationFrame(state.raf);say(message,tone);saveRun('finished',Math.floor(g.distance),0);controls([{id:'dash-again',label:`RUN AGAIN // ${podSkin(g.skinId).name}`},{id:'pod-select',label:'CHANGE POD'}]);}
async function saveRun(status=state.status,progress=0,lives=0){if(!state.identity?.profileId)return;if(isGlobalDash){if(status==='finished'){try{const key=`eras.escape-pod-dash.global.best.${state.identity.profileId}`,prior=Math.max(0,Number(localStorage.getItem(key))||0),next=Math.max(prior,state.score);localStorage.setItem(key,String(next));}catch(_){}}return;}if(!lobbyId)return;try{await fs.setDoc(fs.doc(db,'hostedModeRuns',lobbyId,'players',state.identity.profileId),{profileId:state.identity.profileId,modeId:state.mode.id,score:state.score,status,lives:Math.max(0,Math.floor(lives||0)),progress:Math.max(0,Math.floor(progress||0)),updatedAt:fs.serverTimestamp()},{merge:true});}catch(e){console.debug('Hosted score save',e?.code||e);}}
function entitlementUnlocks(holdingId){return state.entitlements.some(e=>entitlementUsable(e)&&(e.assetHoldingIds||[]).includes(holdingId));}
function offerLocksAsset(holdingId){return state.offers.some(o=>o.active&&['icon_license','bundle'].includes(o.offerType)&&(o.assetHoldingIds||[]).includes(holdingId));}
function renderAssets(){const root=$('#hostAssets');if(!root)return;const assets=state.lobby?.hostAssets||[];if(!assets.length){root.innerHTML='<p class="runtime-list-empty">HOST DID NOT ATTACH ASSETS.</p>';return;}const isHost=state.identity?.profileId===state.lobby?.hostProfileId;root.innerHTML=assets.map(a=>{const m=meta(a.assetId),locked=!isHost&&offerLocksAsset(a.holdingId)&&!entitlementUnlocks(a.holdingId),selected=state.selectedAssetId===a.holdingId;return `<article class="hosted-asset ${locked?'is-locked':''} ${selected?'is-selected':''}"><img data-runtime-holding-preview="${esc(a.holdingId)}" src="${esc(assetPreviewUrl(m))}" alt=""><span><b>${esc(m.name)}</b><small>${locked?'LICENSE REQUIRED':'AVAILABLE IN THIS HOSTED GAME'}</small></span><button type="button" data-host-asset="${esc(a.holdingId)}" ${locked?'disabled':''}>${selected?'ACTIVE':'USE'}</button></article>`;}).join('');for(const a of assets){const img=root.querySelector(`[data-runtime-holding-preview="${CSS.escape(a.holdingId)}"]`);if(img)hydrateVariantPreviewImage(img,meta(a.assetId),a.tint||'#ffffff',96);}}
function offerSummary(o){const parts=[];if(o.playCount)parts.push(`${o.playCount} PLAY${o.playCount===1?'':'S'}`);if(o.lifeCount)parts.push(`${o.lifeCount} ${o.lifeCount===1?'LIFE':'LIVES'}`);if(o.minutes)parts.push(`${o.minutes} MIN`);if(o.permanent)parts.push('PERMANENT');if((o.assetHoldingIds||[]).length)parts.push(`${o.assetHoldingIds.length} ICON${o.assetHoldingIds.length===1?'':'S'}`);return parts.join(' + ')||o.billing.toUpperCase();}
async function loadEntitlements(){if(!state.identity?.profileId){state.entitlements=[];return;}try{const q=fs.query(fs.collection(db,'hostedEntitlements'),fs.where('ownerProfileId','==',state.identity.profileId),fs.limit(100));const s=await fs.getDocs(q);state.entitlements=s.docs.map(d=>({id:d.id,...d.data()})).filter(e=>!e.lobbyId||e.lobbyId===lobbyId);}catch(e){console.debug(e);state.entitlements=[];}}
async function refreshCommerce(){state.offers=await offersForLobby(lobbyId).catch(()=>[]);await loadEntitlements();renderAssets();renderOffers();}
function renderOffers(){const root=$('#hostOffers');if(!root)return;if(!state.offers.length){root.innerHTML='<p class="runtime-list-empty">NO PAID OFFERS. HOSTED ACCESS / ICONS ARE FREE.</p>';return;}root.innerHTML=state.offers.map(o=>{const owned=state.entitlements.some(e=>e.offerId===o.id&&entitlementUsable(e));return `<article class="hosted-offer"><span><b>${esc(o.title)}</b><small>${esc(offerSummary(o))}<br>◈ ${Number(o.priceCredits||0).toLocaleString()} CREDITS</small></span><button type="button" data-buy-offer="${esc(o.id)}">${owned?'BUY AGAIN':'PURCHASE'}</button></article>`;}).join('');}
async function buyOffer(id){if(!state.identity?.profileId)return say('Sign in first.','error');const offer=state.offers.find(o=>o.id===id);if(!offer)return;const exact=`${offer.title}\n${offerSummary(offer)}\n${offer.priceCredits} Credits`;if(!confirm(`PURCHASE HOSTED OFFER?\n\n${exact}\n\nPurchases are deterministic and final once granted.`))return;try{say('Processing hosted Credit purchase…');await purchaseHostedOffer({offerId:id,buyerProfileId:state.identity.profileId});await refreshCommerce();say('Purchase complete. Entitlement added.','ok');}catch(e){console.error(e);say(e?.message||e?.code||'Purchase failed.','error');}}
function renderRules(){const s=state.lobby?.settings||{},m=s.modeSettings||{},root=$('#hostRules'),dash=state.mode?.id==='escape-pod-dash';const entries=Object.entries(m).filter(([k])=>!dash||!['lives','targetDistance'].includes(k));const rows=entries.slice(0,12).map(([k,v])=>{const dashGrid=dash&&k==='lanes';return `<div class="runtime-status-row"><span>${esc(dashGrid?'MOVEMENT GRID':k.replace(/([A-Z])/g,' $1').toUpperCase())}</span><b>${esc(dashGrid?'3 × 3 / 9 POSITIONS':String(v).toUpperCase())}</b></div>`;}).join('');root.innerHTML=(dash?'<div class="runtime-status-row"><span>RUN MODE</span><b>ENDLESS // FIRST CRASH ENDS RUN</b></div>':'')+(rows||(!dash?'<div class="runtime-status-row"><span>MODE</span><b>CUSTOM HOST SETTINGS</b></div>':''));}
function hud(items){$('#gameHud').innerHTML=items.map(x=>`<span>${esc(x)}</span>`).join('');}
function controls(buttons){$('#gameControls').innerHTML=buttons.map(b=>`<button type="button" data-game-action="${esc(b.id)}">${esc(b.label)}</button>`).join('');}
function seeded(seed){let h=2166136261;for(const c of String(seed)){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return()=>((h=Math.imul(h^h>>>15,2246822507),((h^h>>>13)>>>0)/4294967296));}
function startSurface(){const cfg=state.lobby.settings.modeSettings||{},n=cfg.gridSize||15,rand=seeded(lobbyId);const cells=Array(n*n).fill(0);for(let y=0;y<n;y++)for(let x=0;x<n;x++){const i=y*n+x;if(x===0||y===0||x===n-1||y===n-1||(x%2===0&&y%2===0&&rand()>.18))cells[i]=1;}cells[1*n+1]=0;let player={x:1,y:1},dots=new Set(),enemies=[];for(let y=1;y<n-1;y++)for(let x=1;x<n-1;x++)if(!cells[y*n+x]&&(x!==1||y!==1))dots.add(y*n+x);for(let i=0;i<(cfg.enemyCount||3);i++)enemies.push({x:n-2-i%2,y:n-2-Math.floor(i/2)});state.game={type:'surface',n,cells,player,dots,enemies,lives:cfg.lives||3,power:0};renderSurface();say('Use Arrow Keys / WASD or the controls below.');}
function renderSurface(){const g=state.game,n=g.n,root=$('#gameStage');root.innerHTML=`<div class="hosted-maze" style="grid-template-columns:repeat(${n},1fr)">${g.cells.map((wall,i)=>{const x=i%n,y=Math.floor(i/n),cls=['hosted-maze-cell'];if(wall)cls.push('wall');else if(g.dots.has(i))cls.push('dot');if(g.player.x===x&&g.player.y===y)cls.push('player');if(g.enemies.some(e=>e.x===x&&e.y===y))cls.push('enemy');return `<i class="${cls.join(' ')}"></i>`;}).join('')}</div>`;hud([`SCORE ${state.score}`,`DISCOVERIES ${g.dots.size}`,`LIVES ${g.lives}`]);controls([{id:'up',label:'▲'},{id:'left',label:'◀'},{id:'down',label:'▼'},{id:'right',label:'▶'}]);}
function surfaceMove(dx,dy){const g=state.game;if(g.type!=='surface'||g.lives<=0)return;const nx=g.player.x+dx,ny=g.player.y+dy;if(g.cells[ny*g.n+nx])return;g.player={x:nx,y:ny};const idx=ny*g.n+nx;if(g.dots.delete(idx))setScore(state.score+10);for(const e of g.enemies){const opts=[[1,0],[-1,0],[0,1],[0,-1]].map(([x,y])=>({x:e.x+x,y:e.y+y})).filter(p=>!g.cells[p.y*g.n+p.x]);opts.sort((a,b)=>(Math.abs(a.x-g.player.x)+Math.abs(a.y-g.player.y))-(Math.abs(b.x-g.player.x)+Math.abs(b.y-g.player.y)));if(opts[0])Object.assign(e,opts[Math.random()<.7?0:Math.floor(Math.random()*opts.length)]);}if(g.enemies.some(e=>e.x===g.player.x&&e.y===g.player.y)){g.lives--;g.player={x:1,y:1};say(g.lives?'SURFACE CONTACT // LIFE LOST':'RUN ENDED // NO LIVES','error');}if(!g.dots.size){setScore(state.score+1000);state.status='finished';say('SURFACE DISCOVERY COMPLETE.','ok');saveRun('finished',100,g.lives);}else saveRun('playing',0,g.lives);renderSurface();}
function startJeng(){const cfg=state.lobby.settings.modeSettings||{},layers=cfg.layers||18;state.game={type:'jeng',layers:Array.from({length:layers},()=>[1,1,1]),removed:0,stability:100,threshold:cfg.collapseThreshold||65};renderJeng();}
function renderJeng(){const g=state.game;$('#gameStage').innerHTML=`<div class="jeng-stage">${g.layers.map((row,ri)=>`<div class="jeng-layer">${row.map((v,bi)=>`<button class="jeng-block ${v?'':'removed'}" data-jeng="${ri}:${bi}" type="button"></button>`).join('')}</div>`).join('')}</div>`;hud([`SCORE ${state.score}`,`BLOCKS ${g.removed}`,`STABILITY ${Math.max(0,Math.round(g.stability))}%`]);controls([{id:'restart',label:'REBUILD STACK'}]);}
function pullJeng(key){const g=state.game,[ri,bi]=key.split(':').map(Number);if(!g.layers?.[ri]?.[bi]||ri>=g.layers.length-2)return say('Top two layers cannot be pulled.','error');g.layers[ri][bi]=0;g.removed++;const rowRemaining=g.layers[ri].reduce((a,b)=>a+b,0),penalty=rowRemaining===2?1.7:rowRemaining===1?5.5:15;const heightFactor=(g.layers.length-ri)/g.layers.length;g.stability-=penalty*heightFactor;setScore(state.score+Math.round(100*heightFactor));if(g.stability<g.threshold){state.status='finished';say('JENG-STROID COLLAPSE // RUN ENDED','error');saveRun('finished',g.removed,g.removed);}else saveRun('playing',g.removed,g.removed);renderJeng();}
function startSoldoku(){const cfg=state.lobby.settings.modeSettings||{},n=cfg.boardSize||9,boxR=n===6?2:Math.sqrt(n),boxC=n===6?3:Math.sqrt(n);const base=Array.from({length:n},(_,r)=>Array.from({length:n},(_,c)=>(r*boxC+Math.floor(r/boxR)+c)%n+1));const puzzle=base.map(r=>r.slice()),difficulty=cfg.difficulty||'normal',keep=difficulty==='easy'?.58:difficulty==='hard'?.35:.46,rand=seeded(lobbyId+state.identity.profileId);for(let r=0;r<n;r++)for(let c=0;c<n;c++)if(rand()>keep)puzzle[r][c]=0;state.game={type:'soldoku',n,solution:base,puzzle,values:puzzle.map(r=>r.slice()),mistakes:0,limit:cfg.mistakeLimit??3,hints:cfg.hints??3};renderSoldoku();}
function renderSoldoku(){const g=state.game;$('#gameStage').innerHTML=`<div class="soldoku-wrap"><div class="soldoku-grid" style="grid-template-columns:repeat(${g.n},1fr)">${g.values.flatMap((row,r)=>row.map((v,c)=>`<input class="soldoku-cell ${g.puzzle[r][c]?'given':''}" data-sudoku="${r}:${c}" inputmode="numeric" maxlength="1" value="${v||''}" ${g.puzzle[r][c]?'disabled':''}>`)).join('')}</div></div>`;hud([`SCORE ${state.score}`,`MISTAKES ${g.mistakes}/${g.limit||'∞'}`,`HINTS ${g.hints}`]);controls([{id:'hint',label:'USE HINT'},{id:'check',label:'CHECK GRID'}]);}
function checkSudokuCell(el){const g=state.game,[r,c]=el.dataset.sudoku.split(':').map(Number),v=Number(el.value);if(!v){g.values[r][c]=0;el.classList.remove('bad');return;}if(v<1||v>g.n||v!==g.solution[r][c]){g.mistakes++;el.classList.add('bad');setScore(Math.max(0,state.score-25));if(g.limit&&g.mistakes>=g.limit){state.status='finished';say('MISTAKE LIMIT REACHED.','error');saveRun('finished',0,0);}}else{g.values[r][c]=v;el.classList.remove('bad');setScore(state.score+50);}renderSoldoku();}
function sudokuAction(id){const g=state.game;if(id==='hint'&&g.hints>0){for(let r=0;r<g.n;r++){for(let c=0;c<g.n;c++)if(!g.values[r][c]){g.values[r][c]=g.solution[r][c];g.hints--;setScore(state.score+10);renderSoldoku();return;}}}if(id==='check'){const done=g.values.every((row,r)=>row.every((v,c)=>v===g.solution[r][c]));if(done){setScore(state.score+2000);state.status='finished';say('SOLDOKU SOLVED.','ok');saveRun('finished',100,0);}else say('GRID IS NOT COMPLETE YET.','error');}}
function startCanvas(mode){const cfg=state.lobby.settings.modeSettings||{},canvas=document.createElement('canvas');canvas.width=760;canvas.height=520;canvas.className=mode==='sunball'?'sunball-canvas':'dash-canvas';$('#gameStage').replaceChildren(canvas);const ctx=canvas.getContext('2d');if(mode==='sunball'){state.game={type:'sunball',canvas,ctx,x:380,y:110,vx:2.2,vy:0,balls:cfg.balls||3,gravity:cfg.gravity||.22,bumper:cfg.bumperForce||1.8,keys:new Set(),bumpers:[{x:240,y:180,r:34},{x:520,y:200,r:38},{x:380,y:285,r:30}]};controls([{id:'left',label:'LEFT FLIPPER'},{id:'right',label:'RIGHT FLIPPER'},{id:'launch',label:'LAUNCH'}]);}else{state.game={type:'dash',canvas,ctx,row:1,col:1,distance:0,speed:cfg.startSpeed||4,accel:cfg.acceleration||.12,rate:cfg.obstacleRate||1,hazards:[],stars:dashStars(canvas),lastSpawn:0,lastFrame:0,skinId:state.selectedPodSkin,bank:0,hitFlash:0};dashControls();say(`LAUNCHED ${podSkin(state.selectedPodSkin).name} // ENDLESS RUN // FIRST CRASH ENDS THE RUN.`,'ok');}cancelAnimationFrame(state.raf);state.raf=requestAnimationFrame(frame);}
function frame(ts=performance.now()){const g=state.game;if(!g||!['sunball','dash'].includes(g.type))return;const c=g.canvas,ctx=g.ctx;ctx.clearRect(0,0,c.width,c.height);if(g.type==='sunball'){ctx.fillStyle='#030a0d';ctx.fillRect(0,0,c.width,c.height);g.vy+=g.gravity;g.x+=g.vx;g.y+=g.vy;if(g.x<15||g.x>c.width-15)g.vx*=-1;if(g.y<15){g.y=15;g.vy=Math.abs(g.vy);}for(const b of g.bumpers){const dx=g.x-b.x,dy=g.y-b.y,d=Math.hypot(dx,dy);ctx.strokeStyle='#8adfe0';ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.stroke();if(d<b.r+10){const f=g.bumper;g.vx+=(dx/(d||1))*f;g.vy+=(dy/(d||1))*f;setScore(state.score+250);}}if(g.y>c.height+20){g.balls--;if(g.balls<=0){state.status='finished';say('SUNBALL RUN COMPLETE.','error');saveRun('finished',state.score,0);return;}g.x=380;g.y=100;g.vx=2.2;g.vy=0;}ctx.fillStyle='#ffe087';ctx.beginPath();ctx.arc(g.x,g.y,10,0,Math.PI*2);ctx.fill();hud([`SCORE ${state.score}`,`BALLS ${g.balls}`]);}else{const dt=Math.min(40,Math.max(0,g.lastFrame?ts-g.lastFrame:16));g.lastFrame=ts;g.distance+=g.speed*dt*.018;g.speed+=g.accel*dt*.002;drawGalaxy(ctx,g,dt);const spawnEvery=Math.max(300,980/(g.rate*(.86+g.speed*.035)));if(ts-g.lastSpawn>spawnEvery){g.lastSpawn=ts;const types=['asteroid','asteroid','planet','satellite','flare'],occupied=new Set();const count=g.speed>7&&Math.random()<.28?2:1;for(let i=0;i<count;i++){let row,col,key,tries=0;do{row=Math.floor(Math.random()*3);col=Math.floor(Math.random()*3);key=`${row}:${col}`;tries++;}while(occupied.has(key)&&tries<8);occupied.add(key);g.hazards.push({row,col,z:0,type:types[Math.floor(Math.random()*types.length)],spin:Math.random()*Math.PI*2,pathColor:dashPathColor(),hit:false});}}for(const h of g.hazards){const previousZ=h.z;h.z+=g.speed*dt*.000055;drawHazard(ctx,g,h);if(!h.hit&&previousZ<1.04&&h.z>=.90&&h.row===g.row&&h.col===g.col){h.hit=true;g.hitFlash=12;finishDash('ESCAPE POD CRASHED // RUN ENDED','error');return;}}g.hazards=g.hazards.filter(h=>h.z<1.12);if(g.hitFlash>0){g.hitFlash--;ctx.fillStyle=`rgba(255,78,103,${g.hitFlash/38})`;ctx.fillRect(0,0,c.width,c.height);}g.bank*=.82;drawEscapePod(ctx,g);setScore(Math.floor(g.distance));hud([`DISTANCE ${Math.floor(g.distance)}`,`RUN ∞`, `SPEED ${g.speed.toFixed(1)}`,`POD ${podSkin(g.skinId).name}`]);}state.raf=requestAnimationFrame(frame);}
function gameAction(id){const g=state.game;if(!g)return;if(g.type==='surface'){const d={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]}[id];if(d)surfaceMove(...d);}else if(g.type==='jeng'&&id==='restart'){setScore(0);startJeng();}else if(g.type==='soldoku')sudokuAction(id);else if(g.type==='sunball'){if(id==='left')g.vx-=1.2;if(id==='right')g.vx+=1.2;if(id==='launch')g.vy=-5;}else if(g.type==='dash'){if(id==='pod-select'){prepareDash();return;}if(id==='dash-again'){setScore(0);state.status='playing';startCanvas('dash');return;}const direct=id.match(/^pos-([0-2])-([0-2])$/);if(direct){const nr=Number(direct[1]),nc=Number(direct[2]);g.bank=Math.max(-1,Math.min(1,nc-g.col));g.row=nr;g.col=nc;return;}if(id==='left'){g.col=Math.max(0,g.col-1);g.bank=-1;}if(id==='right'){g.col=Math.min(2,g.col+1);g.bank=1;}if(id==='up')g.row=Math.max(0,g.row-1);if(id==='down')g.row=Math.min(2,g.row+1);}}
function startGame(){setScore(0);state.status='playing';switch(state.mode.id){case'surface-discovery':startSurface();break;case'jeng-stroid':startJeng();break;case'sunball':startCanvas('sunball');break;case'soldoku':startSoldoku();break;case'escape-pod-dash':startCanvas('dash');break;default:location.replace(`/game/join/`);}}
async function init(){await loadCatalog();if(isGlobalDash){state.mode=hostedMode('escape-pod-dash');state.lobby={id:'global-escape-pod-dash',hostProfileId:'eras-site',accessOfferId:'',hostAssets:[],settings:{modeSettings:{lanes:3,lives:1,startSpeed:4,acceleration:.12,targetDistance:20000,obstacleRate:1}}};$('#modeTitle').textContent='ESCAPE POD DASH GLOBAL';$('#modeKicker').textContent='GLOBAL // SITE-HOSTED // 24/7';$('#modeDescription').textContent='Blast through an endless galaxy across a 3 × 3 field. Survive as long as possible — the first crash ends the run.';renderRules();watchIdentity(async identity=>{state.identity=identity;if(!identity?.profileId)return say('Sign in to launch Escape Pod Dash Global.','error');await prepareDash();});return;}if(!lobbyId)return say('Missing lobby id.','error');const snap=await fs.getDoc(fs.doc(db,'gameLobbies',lobbyId));if(!snap.exists())return say('Lobby not found.','error');state.lobby={id:snap.id,...snap.data()};state.mode=hostedMode(state.lobby.gameStyle);if(state.mode.runtime!=='hosted')return location.replace(state.mode.runtime==='galactic'?`/game/galactic-dominion/?lobby=${encodeURIComponent(lobbyId)}`:`/game/global/?lobby=${encodeURIComponent(lobbyId)}`);$('#modeTitle').textContent=state.mode.name.toUpperCase();$('#modeKicker').textContent=`${state.mode.short} // HOSTED BY PLAYER`;$('#modeDescription').textContent=state.mode.description;renderRules();watchIdentity(async identity=>{state.identity=identity;if(!identity?.profileId)return say('Sign in to play.','error');try{const entitlementId=await obtainLobbyEntitlement(state.lobby,identity.profileId);await createLobbyMembership(state.lobby,identity.profileId,entitlementId);state.accessLeaseStop?.();state.accessLeaseStop=maintainLobbyMembership(state.lobby,identity.profileId,{onExpired:()=>{say('HOSTED ACCESS EXPIRED. RETURNING TO JOIN.','error');setTimeout(()=>location.replace(`/game/join/?code=${encodeURIComponent(state.lobby.code||'')}`),500);},onError:e=>console.debug('Hosted access lease',e?.code||e)});await refreshCommerce();if(state.mode.id==='escape-pod-dash')await prepareDash();else startGame();}catch(e){console.error(e);say(e?.message||e?.code||'Could not authorize hosted access.','error');setTimeout(()=>location.replace(`/game/join/?code=${encodeURIComponent(state.lobby.code||'')}`),800);}});}
document.addEventListener('click',e=>{const podBuy=e.target.closest('[data-buy-pod]');if(podBuy){buyPodSkin(podBuy.dataset.buyPod);return;}const podSelect=e.target.closest('[data-pod-skin]');if(podSelect){choosePodSkin(podSelect.dataset.podSkin);return;}if(e.target.closest('[data-start-dash]')){if(podOwned(podSkin(state.selectedPodSkin))){setScore(0);state.status='playing';startCanvas('dash');}return;}const buy=e.target.closest('[data-buy-offer]');if(buy){buyOffer(buy.dataset.buyOffer);return;}const asset=e.target.closest('[data-host-asset]');if(asset&&!asset.disabled){state.selectedAssetId=asset.dataset.hostAsset;renderAssets();return;}const action=e.target.closest('[data-game-action]');if(action){gameAction(action.dataset.gameAction);return;}const block=e.target.closest('[data-jeng]');if(block)pullJeng(block.dataset.jeng);});
document.addEventListener('input',e=>{if(e.target.matches('[data-sudoku]'))checkSudokuCell(e.target);});
document.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(document.activeElement?.tagName||''))return;const key=e.key.toLowerCase();let id='';if(state.game?.type==='dash'){const direct={'7':'pos-0-0','8':'pos-0-1','9':'pos-0-2','4':'pos-1-0','5':'pos-1-1','6':'pos-1-2','1':'pos-2-0','2':'pos-2-1','3':'pos-2-2','q':'pos-0-0','e':'pos-0-2','z':'pos-2-0','c':'pos-2-2'};id=direct[key]||((key==='arrowup'||key==='w')?'up':(key==='arrowdown'||key==='s')?'down':(key==='arrowleft'||key==='a')?'left':(key==='arrowright'||key==='d')?'right':'');}else{id=key==='arrowup'||key==='w'?'up':key==='arrowdown'||key==='s'?'down':key==='arrowleft'||key==='a'?'left':key==='arrowright'||key==='d'?'right':key===' '?'jump':'';}if(id){e.preventDefault();gameAction(id);}});
init().catch(e=>{console.error(e);say(e?.message||'Could not load hosted mode.','error');});

window.addEventListener('pagehide',()=>state.accessLeaseStop?.());
