import { db, fs, watchIdentity, safeText } from '/game/assets/js/eras-data.js';
import { hostedMode } from '/game/config/hosted-modes.js?v=1.0.0';
import { offersForLobby, purchaseHostedOffer, entitlementUsable, consumeEntitlement } from '/game/assets/js/hosted-commerce.js?v=1.0.0';
import { assetPreviewUrl } from '/game/assets/js/catalog-assets.js?v=1.0.0';

const $=s=>document.querySelector(s), params=new URLSearchParams(location.search), lobbyId=params.get('lobby')||'';
const state={identity:null,lobby:null,mode:null,offers:[],entitlements:[],catalog:{assets:[]},selectedAssetId:'',score:0,status:'ready',game:null,raf:0,playtimeTimer:null};
const esc=safeText, say=(m,t='')=>{const e=$('#gameFeedback');if(e){e.textContent=String(m).toUpperCase();e.dataset.tone=t;}};
const setScore=v=>{state.score=Math.max(0,Math.floor(Number(v)||0));$('#runScore').textContent=state.score.toLocaleString();};
const meta=id=>state.catalog.assets.find(a=>a.id===id)||{name:id||'Asset',source:'/public-assets/textures/slime_monochrome.png',thumbnail:'/public-assets/textures/slime_monochrome.png'};
async function loadCatalog(){try{const r=await fetch('/public-assets/catalog.json',{cache:'no-store'});if(r.ok)state.catalog=await r.json();}catch(_){}}
async function saveRun(status=state.status,progress=0,lives=0){if(!state.identity?.profileId||!lobbyId)return;try{await fs.setDoc(fs.doc(db,'hostedModeRuns',lobbyId,'players',state.identity.profileId),{profileId:state.identity.profileId,modeId:state.mode.id,score:state.score,status,lives:Math.max(0,Math.floor(lives||0)),progress:Math.max(0,Math.floor(progress||0)),updatedAt:fs.serverTimestamp()},{merge:true});}catch(e){console.debug('Hosted score save',e?.code||e);}}
function entitlementUnlocks(holdingId){return state.entitlements.some(e=>entitlementUsable(e)&&(e.assetHoldingIds||[]).includes(holdingId));}
function offerLocksAsset(holdingId){return state.offers.some(o=>o.active&&['icon_license','bundle'].includes(o.offerType)&&(o.assetHoldingIds||[]).includes(holdingId));}
function renderAssets(){const root=$('#hostAssets');if(!root)return;const assets=state.lobby?.hostAssets||[];if(!assets.length){root.innerHTML='<p class="runtime-list-empty">HOST DID NOT ATTACH ASSETS.</p>';return;}const isHost=state.identity?.profileId===state.lobby?.hostProfileId;root.innerHTML=assets.map(a=>{const m=meta(a.assetId),locked=!isHost&&offerLocksAsset(a.holdingId)&&!entitlementUnlocks(a.holdingId),selected=state.selectedAssetId===a.holdingId;return `<article class="hosted-asset ${locked?'is-locked':''} ${selected?'is-selected':''}" style="--asset-tint:${esc(a.tint||'#ffffff')}"><img src="${esc(assetPreviewUrl(m))}" alt=""><span><b>${esc(m.name)}</b><small>${locked?'LICENSE REQUIRED':'AVAILABLE IN THIS HOSTED GAME'}</small></span><button type="button" data-host-asset="${esc(a.holdingId)}" ${locked?'disabled':''}>${selected?'ACTIVE':'USE'}</button></article>`;}).join('');}
function offerSummary(o){const parts=[];if(o.playCount)parts.push(`${o.playCount} PLAY${o.playCount===1?'':'S'}`);if(o.lifeCount)parts.push(`${o.lifeCount} ${o.lifeCount===1?'LIFE':'LIVES'}`);if(o.minutes)parts.push(`${o.minutes} MIN`);if(o.permanent)parts.push('PERMANENT');if((o.assetHoldingIds||[]).length)parts.push(`${o.assetHoldingIds.length} ICON${o.assetHoldingIds.length===1?'':'S'}`);return parts.join(' + ')||o.billing.toUpperCase();}
async function loadEntitlements(){if(!state.identity?.profileId){state.entitlements=[];return;}try{const q=fs.query(fs.collection(db,'hostedEntitlements'),fs.where('ownerProfileId','==',state.identity.profileId),fs.limit(100));const s=await fs.getDocs(q);state.entitlements=s.docs.map(d=>({id:d.id,...d.data()})).filter(e=>!e.lobbyId||e.lobbyId===lobbyId);}catch(e){console.debug(e);state.entitlements=[];}}
async function refreshCommerce(){state.offers=await offersForLobby(lobbyId).catch(()=>[]);await loadEntitlements();renderAssets();renderOffers();}
function activePlaytimeEntitlement(){return state.entitlements.find(e=>e.lobbyId===lobbyId&&['playtime','bundle'].includes(e.billing)&&Number(e.remainingSeconds||0)>0);}
function stopPlaytimeMeter(){clearInterval(state.playtimeTimer);state.playtimeTimer=null;}
function startPlaytimeMeter(){stopPlaytimeMeter();const e=activePlaytimeEntitlement();if(!e)return;state.playtimeTimer=setInterval(async()=>{const current=activePlaytimeEntitlement();if(!current){stopPlaytimeMeter();return;}try{const ok=await consumeEntitlement(current.id,'seconds',10);if(!ok){stopPlaytimeMeter();say('PURCHASED PLAYTIME EXPIRED.','error');return;}current.remainingSeconds=Math.max(0,Number(current.remainingSeconds||0)-10);if(current.remainingSeconds<=0){stopPlaytimeMeter();say('PURCHASED PLAYTIME EXPIRED.','error');}}catch(err){console.debug('Playtime meter',err?.code||err);}},10000);}
function renderOffers(){const root=$('#hostOffers');if(!root)return;if(!state.offers.length){root.innerHTML='<p class="runtime-list-empty">NO PAID OFFERS. HOSTED ACCESS / ICONS ARE FREE.</p>';return;}root.innerHTML=state.offers.map(o=>{const owned=state.entitlements.some(e=>e.offerId===o.id&&entitlementUsable(e));return `<article class="hosted-offer"><span><b>${esc(o.title)}</b><small>${esc(offerSummary(o))}<br>◈ ${Number(o.priceCredits||0).toLocaleString()} CREDITS</small></span><button type="button" data-buy-offer="${esc(o.id)}">${owned?'BUY AGAIN':'PURCHASE'}</button></article>`;}).join('');}
async function buyOffer(id){if(!state.identity?.profileId)return say('Sign in first.','error');const offer=state.offers.find(o=>o.id===id);if(!offer)return;const exact=`${offer.title}\n${offerSummary(offer)}\n${offer.priceCredits} Credits`;if(!confirm(`PURCHASE HOSTED OFFER?\n\n${exact}\n\nPurchases are deterministic and final once granted.`))return;try{say('Processing hosted Credit purchase…');await purchaseHostedOffer({offerId:id,buyerProfileId:state.identity.profileId});await refreshCommerce();say('Purchase complete. Entitlement added.','ok');}catch(e){console.error(e);say(e?.message||e?.code||'Purchase failed.','error');}}
function renderRules(){const s=state.lobby?.settings||{},m=s.modeSettings||{},root=$('#hostRules');const rows=Object.entries(m).slice(0,12).map(([k,v])=>`<div class="runtime-status-row"><span>${esc(k.replace(/([A-Z])/g,' $1').toUpperCase())}</span><b>${esc(String(v).toUpperCase())}</b></div>`).join('');root.innerHTML=rows||'<div class="runtime-status-row"><span>MODE</span><b>CUSTOM HOST SETTINGS</b></div>';}
function hud(items){$('#gameHud').innerHTML=items.map(x=>`<span>${esc(x)}</span>`).join('');}
function controls(buttons){$('#gameControls').innerHTML=buttons.map(b=>`<button type="button" data-game-action="${esc(b.id)}">${esc(b.label)}</button>`).join('');}
function seeded(seed){let h=2166136261;for(const c of String(seed)){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return()=>((h=Math.imul(h^h>>>15,2246822507),((h^h>>>13)>>>0)/4294967296));}
function startSurface(){const cfg=state.lobby.settings.modeSettings||{},n=cfg.gridSize||15,rand=seeded(lobbyId);const cells=Array(n*n).fill(0);for(let y=0;y<n;y++)for(let x=0;x<n;x++){const i=y*n+x;if(x===0||y===0||x===n-1||y===n-1||(x%2===0&&y%2===0&&rand()>.18))cells[i]=1;}cells[1*n+1]=0;let player={x:1,y:1},dots=new Set(),enemies=[];for(let y=1;y<n-1;y++)for(let x=1;x<n-1;x++)if(!cells[y*n+x]&&(x!==1||y!==1))dots.add(y*n+x);for(let i=0;i<(cfg.enemyCount||3);i++)enemies.push({x:n-2-i%2,y:n-2-Math.floor(i/2)});state.game={type:'surface',n,cells,player,dots,enemies,lives:cfg.lives||3,power:0};renderSurface();say('Use Arrow Keys / WASD or the controls below.');}
function renderSurface(){const g=state.game,n=g.n,root=$('#gameStage');root.innerHTML=`<div class="hosted-maze" style="grid-template-columns:repeat(${n},1fr)">${g.cells.map((wall,i)=>{const x=i%n,y=Math.floor(i/n),cls=['hosted-maze-cell'];if(wall)cls.push('wall');else if(g.dots.has(i))cls.push('dot');if(g.player.x===x&&g.player.y===y)cls.push('player');if(g.enemies.some(e=>e.x===x&&e.y===y))cls.push('enemy');return `<i class="${cls.join(' ')}"></i>`;}).join('')}</div>`;hud([`SCORE ${state.score}`,`DISCOVERIES ${g.dots.size}`,`LIVES ${g.lives}`]);controls([{id:'up',label:'▲'},{id:'left',label:'◀'},{id:'down',label:'▼'},{id:'right',label:'▶'}]);}
function surfaceMove(dx,dy){const g=state.game;if(g.type!=='surface'||g.lives<=0)return;const nx=g.player.x+dx,ny=g.player.y+dy;if(g.cells[ny*g.n+nx])return;g.player={x:nx,y:ny};const idx=ny*g.n+nx;if(g.dots.delete(idx))setScore(state.score+10);for(const e of g.enemies){const opts=[[1,0],[-1,0],[0,1],[0,-1]].map(([x,y])=>({x:e.x+x,y:e.y+y})).filter(p=>!g.cells[p.y*g.n+p.x]);opts.sort((a,b)=>(Math.abs(a.x-g.player.x)+Math.abs(a.y-g.player.y))-(Math.abs(b.x-g.player.x)+Math.abs(b.y-g.player.y)));if(opts[0])Object.assign(e,opts[Math.random()<.7?0:Math.floor(Math.random()*opts.length)]);}if(g.enemies.some(e=>e.x===g.player.x&&e.y===g.player.y)){g.lives--;g.player={x:1,y:1};say(g.lives?'SURFACE CONTACT // LIFE LOST':'RUN ENDED // NO LIVES','error');}if(!g.dots.size){setScore(state.score+1000);state.status='finished';say('SURFACE DISCOVERY COMPLETE.','ok');saveRun('finished',100,g.lives);}else saveRun('playing',0,g.lives);renderSurface();}
function startJeng(){const cfg=state.lobby.settings.modeSettings||{},layers=cfg.layers||18;state.game={type:'jeng',layers:Array.from({length:layers},()=>[1,1,1]),removed:0,stability:100,threshold:cfg.collapseThreshold||65};renderJeng();}
function renderJeng(){const g=state.game;$('#gameStage').innerHTML=`<div class="jeng-stage">${g.layers.map((row,ri)=>`<div class="jeng-layer">${row.map((v,bi)=>`<button class="jeng-block ${v?'':'removed'}" data-jeng="${ri}:${bi}" type="button"></button>`).join('')}</div>`).join('')}</div>`;hud([`SCORE ${state.score}`,`BLOCKS ${g.removed}`,`STABILITY ${Math.max(0,Math.round(g.stability))}%`]);controls([{id:'restart',label:'REBUILD STACK'}]);}
function pullJeng(key){const g=state.game,[ri,bi]=key.split(':').map(Number);if(!g.layers?.[ri]?.[bi]||ri>=g.layers.length-2)return say('Top two layers cannot be pulled.','error');g.layers[ri][bi]=0;g.removed++;const rowRemaining=g.layers[ri].reduce((a,b)=>a+b,0),penalty=rowRemaining===2?1.7:rowRemaining===1?5.5:15;const heightFactor=(g.layers.length-ri)/g.layers.length;g.stability-=penalty*heightFactor;setScore(state.score+Math.round(100*heightFactor));if(g.stability<g.threshold){state.status='finished';say('JENG-STROID COLLAPSE // RUN ENDED','error');saveRun('finished',g.removed,g.removed);}else saveRun('playing',g.removed,g.removed);renderJeng();}
function startSoldoku(){const cfg=state.lobby.settings.modeSettings||{},n=cfg.boardSize||9,boxR=n===6?2:Math.sqrt(n),boxC=n===6?3:Math.sqrt(n);const base=Array.from({length:n},(_,r)=>Array.from({length:n},(_,c)=>(r*boxC+Math.floor(r/boxR)+c)%n+1));const puzzle=base.map(r=>r.slice()),difficulty=cfg.difficulty||'normal',keep=difficulty==='easy'?.58:difficulty==='hard'?.35:.46,rand=seeded(lobbyId+state.identity.profileId);for(let r=0;r<n;r++)for(let c=0;c<n;c++)if(rand()>keep)puzzle[r][c]=0;state.game={type:'soldoku',n,solution:base,puzzle,values:puzzle.map(r=>r.slice()),mistakes:0,limit:cfg.mistakeLimit??3,hints:cfg.hints??3};renderSoldoku();}
function renderSoldoku(){const g=state.game;$('#gameStage').innerHTML=`<div class="soldoku-wrap"><div class="soldoku-grid" style="grid-template-columns:repeat(${g.n},1fr)">${g.values.flatMap((row,r)=>row.map((v,c)=>`<input class="soldoku-cell ${g.puzzle[r][c]?'given':''}" data-sudoku="${r}:${c}" inputmode="numeric" maxlength="1" value="${v||''}" ${g.puzzle[r][c]?'disabled':''}>`)).join('')}</div></div>`;hud([`SCORE ${state.score}`,`MISTAKES ${g.mistakes}/${g.limit||'∞'}`,`HINTS ${g.hints}`]);controls([{id:'hint',label:'USE HINT'},{id:'check',label:'CHECK GRID'}]);}
function checkSudokuCell(el){const g=state.game,[r,c]=el.dataset.sudoku.split(':').map(Number),v=Number(el.value);if(!v){g.values[r][c]=0;el.classList.remove('bad');return;}if(v<1||v>g.n||v!==g.solution[r][c]){g.mistakes++;el.classList.add('bad');setScore(Math.max(0,state.score-25));if(g.limit&&g.mistakes>=g.limit){state.status='finished';say('MISTAKE LIMIT REACHED.','error');saveRun('finished',0,0);}}else{g.values[r][c]=v;el.classList.remove('bad');setScore(state.score+50);}renderSoldoku();}
function sudokuAction(id){const g=state.game;if(id==='hint'&&g.hints>0){for(let r=0;r<g.n;r++){for(let c=0;c<g.n;c++)if(!g.values[r][c]){g.values[r][c]=g.solution[r][c];g.hints--;setScore(state.score+10);renderSoldoku();return;}}}if(id==='check'){const done=g.values.every((row,r)=>row.every((v,c)=>v===g.solution[r][c]));if(done){setScore(state.score+2000);state.status='finished';say('SOLDOKU SOLVED.','ok');saveRun('finished',100,0);}else say('GRID IS NOT COMPLETE YET.','error');}}
function startCanvas(mode){const cfg=state.lobby.settings.modeSettings||{},canvas=document.createElement('canvas');canvas.width=760;canvas.height=520;canvas.className=mode==='sunball'?'sunball-canvas':'dash-canvas';$('#gameStage').replaceChildren(canvas);const ctx=canvas.getContext('2d');if(mode==='sunball'){state.game={type:'sunball',canvas,ctx,x:380,y:110,vx:2.2,vy:0,balls:cfg.balls||3,gravity:cfg.gravity||.22,bumper:cfg.bumperForce||1.8,keys:new Set(),bumpers:[{x:240,y:180,r:34},{x:520,y:200,r:38},{x:380,y:285,r:30}]};controls([{id:'left',label:'LEFT FLIPPER'},{id:'right',label:'RIGHT FLIPPER'},{id:'launch',label:'LAUNCH'}]);}else{state.game={type:'dash',canvas,ctx,lane:Math.floor((cfg.lanes||3)/2),lanes:cfg.lanes||3,lives:cfg.lives||3,distance:0,speed:cfg.startSpeed||4,accel:cfg.acceleration||.12,target:cfg.targetDistance||2500,rate:cfg.obstacleRate||1,obstacles:[],jump:0,lastSpawn:0};controls([{id:'left',label:'◀ LANE'},{id:'jump',label:'JUMP'},{id:'right',label:'LANE ▶'}]);}cancelAnimationFrame(state.raf);state.raf=requestAnimationFrame(frame);}
function frame(){const g=state.game;if(!g||!['sunball','dash'].includes(g.type))return;const c=g.canvas,ctx=g.ctx;ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='#030a0d';ctx.fillRect(0,0,c.width,c.height);if(g.type==='sunball'){g.vy+=g.gravity;g.x+=g.vx;g.y+=g.vy;if(g.x<15||g.x>c.width-15)g.vx*=-1;if(g.y<15){g.y=15;g.vy=Math.abs(g.vy);}for(const b of g.bumpers){const dx=g.x-b.x,dy=g.y-b.y,d=Math.hypot(dx,dy);ctx.strokeStyle='#8adfe0';ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.stroke();if(d<b.r+10){const f=g.bumper;g.vx+=(dx/(d||1))*f;g.vy+=(dy/(d||1))*f;setScore(state.score+250);}}if(g.y>c.height+20){g.balls--;if(g.balls<=0){state.status='finished';say('SUNBALL RUN COMPLETE.','error');saveRun('finished',state.score,0);return;}g.x=380;g.y=100;g.vx=2.2;g.vy=0;}ctx.fillStyle='#ffe087';ctx.beginPath();ctx.arc(g.x,g.y,10,0,Math.PI*2);ctx.fill();hud([`SCORE ${state.score}`,`BALLS ${g.balls}`]);}else{g.distance+=g.speed*.18;g.speed+=g.accel*.002;if(performance.now()-g.lastSpawn>900/g.rate){g.lastSpawn=performance.now();g.obstacles.push({lane:Math.floor(Math.random()*g.lanes),y:-30});}for(const o of g.obstacles)o.y+=g.speed;g.obstacles=g.obstacles.filter(o=>o.y<c.height+50);const laneW=c.width/g.lanes;ctx.strokeStyle='#18383e';for(let i=1;i<g.lanes;i++){ctx.beginPath();ctx.moveTo(i*laneW,0);ctx.lineTo(i*laneW,c.height);ctx.stroke();}for(const o of g.obstacles){ctx.fillStyle='#a84456';ctx.fillRect(o.lane*laneW+laneW*.18,o.y,laneW*.64,34);if(o.lane===g.lane&&o.y>c.height-100&&o.y<c.height-55&&g.jump<=0){o.y=c.height+100;g.lives--;say('COLLISION // LIFE LOST','error');if(g.lives<=0){state.status='finished';saveRun('finished',Math.floor(g.distance),0);return;}}}if(g.jump>0)g.jump--;ctx.fillStyle='#9fe4e3';ctx.fillRect(g.lane*laneW+laneW*.32,c.height-70-(g.jump?32:0),laneW*.36,28);setScore(Math.floor(g.distance));hud([`DISTANCE ${Math.floor(g.distance)}/${g.target}`,`LIVES ${g.lives}`,`SPEED ${g.speed.toFixed(1)}`]);if(g.distance>=g.target){state.status='finished';say('ESCAPE CORRIDOR CLEARED.','ok');saveRun('finished',100,g.lives);return;}}state.raf=requestAnimationFrame(frame);}
function gameAction(id){const g=state.game;if(!g)return;if(g.type==='surface'){const d={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]}[id];if(d)surfaceMove(...d);}else if(g.type==='jeng'&&id==='restart'){setScore(0);startJeng();}else if(g.type==='soldoku')sudokuAction(id);else if(g.type==='sunball'){if(id==='left')g.vx-=1.2;if(id==='right')g.vx+=1.2;if(id==='launch')g.vy=-5;}else if(g.type==='dash'){if(id==='left')g.lane=Math.max(0,g.lane-1);if(id==='right')g.lane=Math.min(g.lanes-1,g.lane+1);if(id==='jump'&&!g.jump)g.jump=28;}}
function startGame(){setScore(0);state.status='playing';switch(state.mode.id){case'surface-discovery':startSurface();break;case'jeng-stroid':startJeng();break;case'sunball':startCanvas('sunball');break;case'soldoku':startSoldoku();break;case'escape-pod-dash':startCanvas('dash');break;default:location.replace(`/game/join/`);}}
async function init(){if(!lobbyId)return say('Missing lobby id.','error');await loadCatalog();const snap=await fs.getDoc(fs.doc(db,'gameLobbies',lobbyId));if(!snap.exists())return say('Lobby not found.','error');state.lobby={id:snap.id,...snap.data()};state.mode=hostedMode(state.lobby.gameStyle);if(state.mode.runtime!=='hosted')return location.replace(state.mode.runtime==='galactic'?`/game/galactic-dominion/?lobby=${encodeURIComponent(lobbyId)}`:`/game/global/?lobby=${encodeURIComponent(lobbyId)}`);$('#modeTitle').textContent=state.mode.name.toUpperCase();$('#modeKicker').textContent=`${state.mode.short} // HOSTED BY PLAYER`;$('#modeDescription').textContent=state.mode.description;renderRules();watchIdentity(async identity=>{state.identity=identity;if(!identity?.profileId)return say('Sign in to play.','error');const member=await fs.getDoc(fs.doc(db,'gameLobbies',lobbyId,'members',identity.profileId));if(!member.exists())return location.replace(`/game/join/?code=${encodeURIComponent(state.lobby.code||'')}`);await refreshCommerce();startPlaytimeMeter();startGame();});}
document.addEventListener('click',e=>{const buy=e.target.closest('[data-buy-offer]');if(buy){buyOffer(buy.dataset.buyOffer);return;}const asset=e.target.closest('[data-host-asset]');if(asset&&!asset.disabled){state.selectedAssetId=asset.dataset.hostAsset;renderAssets();return;}const action=e.target.closest('[data-game-action]');if(action){gameAction(action.dataset.gameAction);return;}const block=e.target.closest('[data-jeng]');if(block)pullJeng(block.dataset.jeng);});
document.addEventListener('input',e=>{if(e.target.matches('[data-sudoku]'))checkSudokuCell(e.target);});
document.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(document.activeElement?.tagName||''))return;const key=e.key.toLowerCase();const id=key==='arrowup'||key==='w'?'up':key==='arrowdown'||key==='s'?'down':key==='arrowleft'||key==='a'?'left':key==='arrowright'||key==='d'?'right':key===' '?'jump':'';if(id){e.preventDefault();gameAction(id);}});
init().catch(e=>{console.error(e);say(e?.message||'Could not load hosted mode.','error');});

window.addEventListener('pagehide',stopPlaytimeMeter);
