import { db, fs, watchIdentity, safeText, avatarSvg } from '/game/assets/js/eras-data.js';
import { defaultHostedWorldSettings, settingsFromHostForm, DEFAULT_ICON_JSON, DEFAULT_SLIME_ICON_JSON } from '/game/config/world-settings.js?v=2.1.0';

const $ = s => document.querySelector(s);
const state = { identity: null, lobby: null, heartbeat: null, content: defaultHostedWorldSettings() };
const say = (message, tone = '') => { const el = $('#hostFeedback'); if (!el) return; el.textContent = String(message).toUpperCase(); el.dataset.tone = tone; };
const esc = safeText;
const jsonPretty = value => { try { return JSON.stringify(typeof value === 'string' ? JSON.parse(value) : value, null, 2); } catch (_) { return String(value || ''); } };
const slug = value => String(value || '').toLowerCase().trim().replace(/[^a-z0-9_-]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 48);
function code(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let out='';for(let i=0;i<6;i++)out+=chars[Math.floor(Math.random()*chars.length)];return out;}
function parseIcon(raw){ const text = String(raw || '').trim(); const parsed = JSON.parse(text); if (!parsed || parsed.version !== 1 || !Array.isArray(parsed.layers) || !parsed.layers.length) throw new Error('Icon JSON must use the LCS version 1 layer format.'); return JSON.stringify(parsed); }
function areaOptions(selected=''){ return state.content.areas.map(a => `<option value="${esc(a.id)}" ${a.id===selected?'selected':''}>${esc(a.name)}</option>`).join(''); }
function itemOptions(selected=''){ return state.content.items.map(i => `<option value="${esc(i.id)}" ${i.id===selected?'selected':''}>${esc(i.name)}</option>`).join(''); }
function iconPreview(iconJson, name){ try { return avatarSvg({ displayName:name || 'ICON', avatarJson:iconJson }); } catch (_) { return avatarSvg({ displayName:'?', avatarJson:DEFAULT_ICON_JSON }); } }

function renderAreas(){ const root=$('#areaDefinitions'); if(!root)return; root.innerHTML=state.content.areas.map((a,i)=>`<article class="creator-definition" data-area-index="${i}"><header><b>${esc(a.name)}</b><button type="button" data-remove-area="${i}">REMOVE</button></header><div class="runtime-split"><label class="runtime-field"><span>AREA ID</span><input data-area="id" value="${esc(a.id)}"></label><label class="runtime-field"><span>AREA NAME</span><input data-area="name" value="${esc(a.name)}"></label></div><div class="creator-quad"><label class="runtime-field"><span>MIN X</span><input type="number" step="0.1" data-area="minX" value="${a.minX}"></label><label class="runtime-field"><span>MAX X</span><input type="number" step="0.1" data-area="maxX" value="${a.maxX}"></label><label class="runtime-field"><span>MIN Y</span><input type="number" step="0.1" data-area="minY" value="${a.minY}"></label><label class="runtime-field"><span>MAX Y</span><input type="number" step="0.1" data-area="maxY" value="${a.maxY}"></label></div></article>`).join(''); }
function renderItems(){ const root=$('#itemDefinitions'); if(!root)return; root.innerHTML=state.content.items.map((item,i)=>`<article class="creator-definition" data-item-index="${i}"><header><span class="creator-icon-preview">${iconPreview(item.iconJson,item.name)}</span><b>${esc(item.name)}</b><button type="button" data-remove-item="${i}">REMOVE</button></header><div class="runtime-split"><label class="runtime-field"><span>ITEM ID</span><input data-item="id" value="${esc(item.id)}"></label><label class="runtime-field"><span>NAME</span><input data-item="name" value="${esc(item.name)}"></label></div><div class="runtime-split"><label class="runtime-field"><span>TYPE</span><select data-item="kind"><option value="material" ${item.kind==='material'?'selected':''}>MATERIAL</option><option value="consumable" ${item.kind==='consumable'?'selected':''}>POTION / CONSUMABLE</option><option value="equipment" ${item.kind==='equipment'?'selected':''}>EQUIPMENT</option></select></label><label class="runtime-field"><span>EQUIPMENT SLOT</span><select data-item="equipmentSlot"><option value="">NONE</option><option value="weapon" ${item.equipmentSlot==='weapon'?'selected':''}>WEAPON</option></select></label></div><label class="runtime-field"><span>DESCRIPTION</span><input data-item="description" value="${esc(item.description)}"></label><div class="creator-quad"><label class="runtime-field"><span>HEAL HP</span><input type="number" min="0" max="50" data-item="healAmount" value="${item.healAmount||0}"></label><label class="runtime-field"><span>DMG MIN</span><input type="number" min="0" max="99" data-item="damageMin" value="${item.damageMin||0}"></label><label class="runtime-field"><span>DMG MAX</span><input type="number" min="0" max="99" data-item="damageMax" value="${item.damageMax||0}"></label><span></span></div><label class="runtime-field"><span>LCS JSON ICON // ONE ICON PER ITEM</span><textarea data-item="iconJson" class="creator-json">${esc(jsonPretty(item.iconJson))}</textarea></label></article>`).join(''); }
function renderMobs(){
  const root=$('#mobDefinitions'); if(!root)return;
  root.innerHTML=state.content.mobs.map((mob,i)=>{
    const drops=(mob.drops||[]).map((drop,di)=>`<div class="creator-inline-row" data-drop-index="${di}"><label class="runtime-field"><span>ITEM</span><select data-drop="itemId">${itemOptions(drop.itemId)}</select></label><label class="runtime-field"><span>DROP %</span><input type="number" min="0" max="100" step="0.1" data-drop="chancePct" value="${Math.round(Number(drop.chance||0)*100000)/1000}"></label><label class="runtime-field"><span>QTY</span><input type="number" min="1" max="99" data-drop="quantity" value="${Math.max(1,Number(drop.quantity||1))}"></label><button type="button" class="creator-row-remove" data-remove-drop="${di}">REMOVE</button></div>`).join('');
    return `<article class="creator-definition" data-mob-index="${i}"><header><span class="creator-icon-preview">${iconPreview(mob.iconJson,mob.name)}</span><b>${esc(mob.name)}</b><button type="button" data-remove-mob="${i}">REMOVE</button></header><div class="runtime-split"><label class="runtime-field"><span>MOB ID</span><input data-mob="id" value="${esc(mob.id)}"></label><label class="runtime-field"><span>NAME</span><input data-mob="name" value="${esc(mob.name)}"></label></div><div class="creator-quad"><label class="runtime-field"><span>HP</span><input type="number" min="1" max="100" data-mob="maxHp" value="${mob.maxHp}"></label><label class="runtime-field"><span>DAMAGE</span><input type="number" min="0" max="50" data-mob="damage" value="${mob.damage}"></label><label class="runtime-field"><span>ATTACK RANGE</span><input type="number" min="1" max="40" step="0.5" data-mob="attackRange" value="${mob.attackRange}"></label><label class="runtime-field"><span>SPAWN COUNT</span><input type="number" min="0" max="24" data-mob="spawnCount" value="${mob.spawnCount}"></label></div><div class="runtime-split"><label class="runtime-field"><span>SPAWN AREA</span><select data-mob="areaId">${areaOptions(mob.areaId)}</select><small>Spawn count above applies to this named area.</small></label><label class="runtime-field"><span>RESPAWN TURNS</span><input type="number" min="1" max="30" data-mob="respawnTurns" value="${mob.respawnTurns}"></label></div><label class="runtime-field"><span>LOCAL CURRENCY / KILL</span><input type="number" min="0" max="10000" data-mob="killReward" value="${mob.killReward||0}"></label><section class="creator-subsection"><div class="creator-section-head"><div><b>DROP TABLE</b><small>Independent chance per item. Custom-world drops never enter Global inventory.</small></div><button type="button" data-add-drop="${i}">+ DROP</button></div><div class="creator-inline-list">${drops||'<div class="runtime-list-empty">NO ITEM DROPS</div>'}</div></section><label class="runtime-field"><span>LCS JSON ICON // ONE ICON PER MOB</span><textarea data-mob="iconJson" class="creator-json">${esc(jsonPretty(mob.iconJson))}</textarea></label></article>`;
  }).join('');
}
function renderTerminals(){
  const root=$('#terminalDefinitions'); if(!root)return;
  root.innerHTML=state.content.terminals.map((t,i)=>{
    const offers=(t.offers||[]).map((offer,oi)=>`<div class="creator-inline-row" data-offer-index="${oi}"><label class="runtime-field"><span>DIRECTION</span><select data-offer="direction"><option value="buy" ${offer.direction==='buy'?'selected':''}>BUY</option><option value="sell" ${offer.direction==='sell'?'selected':''}>SELL</option></select></label><label class="runtime-field"><span>ITEM</span><select data-offer="itemId">${itemOptions(offer.itemId)}</select></label><label class="runtime-field"><span>PRICE</span><input type="number" min="1" max="100000" data-offer="price" value="${Math.max(1,Number(offer.price||1))}"></label><button type="button" class="creator-row-remove" data-remove-offer="${oi}">REMOVE</button></div>`).join('');
    return `<article class="creator-definition" data-terminal-index="${i}"><header><b>${esc(t.name)}</b><button type="button" data-remove-terminal="${i}">REMOVE</button></header><div class="runtime-split"><label class="runtime-field"><span>TACTICAL TARGET ID</span><input data-terminal="id" value="${esc(t.id)}"><small>Must match an interactable terminal object on the chosen map.</small></label><label class="runtime-field"><span>NAME</span><input data-terminal="name" value="${esc(t.name)}"></label></div><label class="runtime-field"><span>SUBTITLE</span><input data-terminal="subtitle" value="${esc(t.subtitle||'WORLD TERMINAL')}"></label><section class="creator-subsection"><div class="creator-section-head"><div><b>SHOP OFFERS</b><small>Uses this world's local currency only.</small></div><button type="button" data-add-offer="${i}">+ OFFER</button></div><div class="creator-inline-list">${offers||'<div class="runtime-list-empty">NO SHOP OFFERS</div>'}</div></section></article>`;
  }).join('');
}
function renderContent(){ renderAreas(); renderItems(); renderMobs(); renderTerminals(); }

function syncFromDom(){
  const previousAreaIds=state.content.areas.map(a=>a.id), previousItemIds=state.content.items.map(i=>i.id);
  document.querySelectorAll('[data-area-index]').forEach(card=>{const a=state.content.areas[Number(card.dataset.areaIndex)];card.querySelectorAll('[data-area]').forEach(input=>a[input.dataset.area]=input.type==='number'?Number(input.value):input.value);a.id=slug(a.id)||'area';});
  document.querySelectorAll('[data-item-index]').forEach(card=>{const item=state.content.items[Number(card.dataset.itemIndex)];card.querySelectorAll('[data-item]').forEach(input=>{const key=input.dataset.item;if(key==='iconJson') item[key]=parseIcon(input.value); else item[key]=input.type==='number'?Number(input.value):input.value;});item.id=slug(item.id)||'item';});
  const areaIdMap=new Map(previousAreaIds.map((id,i)=>[id,state.content.areas[i]?.id||id]));
  const itemIdMap=new Map(previousItemIds.map((id,i)=>[id,state.content.items[i]?.id||id]));
  document.querySelectorAll('[data-mob-index]').forEach(card=>{
    const mob=state.content.mobs[Number(card.dataset.mobIndex)];
    card.querySelectorAll('[data-mob]').forEach(input=>{const key=input.dataset.mob;if(key==='iconJson')mob[key]=parseIcon(input.value);else mob[key]=input.type==='number'?Number(input.value):input.value;});
    mob.id=slug(mob.id)||'mob'; mob.areaId=areaIdMap.get(mob.areaId)||mob.areaId; mob.drops=[];
    card.querySelectorAll('[data-drop-index]').forEach(row=>{const d={itemId:'',chance:0,quantity:1};row.querySelectorAll('[data-drop]').forEach(input=>{const key=input.dataset.drop;if(key==='chancePct')d.chance=Math.max(0,Math.min(100,Number(input.value)||0))/100;else d[key]=input.type==='number'?Number(input.value):input.value;});d.itemId=itemIdMap.get(d.itemId)||d.itemId;if(d.itemId)mob.drops.push(d);});
  });
  document.querySelectorAll('[data-terminal-index]').forEach(card=>{
    const t=state.content.terminals[Number(card.dataset.terminalIndex)];
    card.querySelectorAll('[data-terminal]').forEach(input=>t[input.dataset.terminal]=input.value); t.id=slug(t.id)||'terminal'; t.offers=[];
    card.querySelectorAll('[data-offer-index]').forEach((row,oi)=>{const o={id:`offer-${oi+1}`,direction:'buy',itemId:'',price:1};row.querySelectorAll('[data-offer]').forEach(input=>o[input.dataset.offer]=input.type==='number'?Number(input.value):input.value);o.itemId=itemIdMap.get(o.itemId)||o.itemId;o.id=slug(`${o.direction}-${o.itemId}-${oi+1}`);if(o.itemId)t.offers.push(o);});
  });
}

function settingsSummary(s){return `HP ${s.player.maxHp} // ENERGY ${s.player.energyPerTurn} // MOVE ${s.player.maxWalkDistance} // ${s.mobs.length} MOB TYPES // ${s.items.length} ITEMS // ${s.terminals.length} TERMINALS // ${esc(s.currency.name)}`;}
function render(){const box=$('#lobbyStatus');if(!box)return;if(!state.lobby){box.innerHTML='<div class="runtime-list-empty">NO ACTIVE LOBBY.</div>';return;}const l=state.lobby;const href=location.pathname.startsWith('/game-mobile/')?`/game-mobile/global/?lobby=${encodeURIComponent(l.id)}`:`/game/global/?lobby=${encodeURIComponent(l.id)}`;box.innerHTML=`<div class="runtime-status-row"><span>LOBBY</span><b>${esc(l.name)}</b></div><div class="runtime-status-row"><span>JOIN CODE</span><b class="lobby-code">${l.code}</b></div><div class="runtime-status-row"><span>WORLD RULES</span><b>${settingsSummary(l.settings)}</b></div><div class="runtime-status-row"><span>ECONOMY</span><b>WORLD-LOCAL ONLY // E.R.A.S. CREDITS DISABLED</b></div><div class="runtime-actions"><a class="runtime-primary" style="display:grid;place-items:center;text-decoration:none;flex:1" href="${href}">ENTER GAME</a><button id="closeLobby" class="runtime-secondary runtime-danger" type="button">CLOSE LOBBY</button></div>`;$('#closeLobby').onclick=closeLobby;}
async function closeLobby(){if(!state.lobby||!state.identity)return;try{await fs.updateDoc(fs.doc(db,'gameLobbies',state.lobby.id),{status:'closed',updatedAt:fs.serverTimestamp(),lastHeartbeatAt:fs.serverTimestamp()});clearInterval(state.heartbeat);state.lobby=null;render();say('Lobby closed.','ok');}catch(e){console.error(e);say(`Could not close lobby: ${e.code||e.message}`,'error');}}
async function createLobby(event){event.preventDefault();if(!state.identity?.profileId)return say('Sign in with Google first.','error');try{syncFromDom();}catch(e){return say(e.message,'error');}const id=crypto.randomUUID(),joinCode=code(),name=$('#lobbyName').value.trim().slice(0,50)||'E.R.A.S. Game';const settings=settingsFromHostForm(document,state.content);const serialized=JSON.stringify(settings);if(serialized.length>700000)return say('World definition is too large. Reduce icon layers/content.','error');const lobby={name,code:joinCode,hostProfileId:state.identity.profileId,visibility:$('#visibility').value,maxPlayers:Number($('#maxPlayers').value),mapId:$('#mapId').value,gameStyle:$('#gameStyle').value,description:$('#description').value.trim().slice(0,240),settings,status:'open',createdAt:fs.serverTimestamp(),updatedAt:fs.serverTimestamp(),lastHeartbeatAt:fs.serverTimestamp()};try{say('Creating modular world…');await fs.setDoc(fs.doc(db,'gameLobbies',id),lobby);await fs.setDoc(fs.doc(db,'gameLobbies',id,'members',state.identity.profileId),{profileId:state.identity.profileId,role:'host',joinedAt:fs.serverTimestamp(),lastSeenAt:fs.serverTimestamp()});state.lobby={id,...lobby,createdAt:null,updatedAt:null,lastHeartbeatAt:null};render();say('World created. Custom content is isolated from E.R.A.S. Credits and Global inventory.','ok');clearInterval(state.heartbeat);state.heartbeat=setInterval(()=>{if(state.lobby)fs.updateDoc(fs.doc(db,'gameLobbies',state.lobby.id),{lastHeartbeatAt:fs.serverTimestamp(),updatedAt:fs.serverTimestamp()}).catch(()=>{});},20000);}catch(e){console.error(e);say(`Could not create lobby: ${e.code||e.message}`,'error');}}

$('#hostForm')?.addEventListener('submit',createLobby);
$('#addArea')?.addEventListener('click',()=>{try{syncFromDom();}catch(e){return say(e.message,'error');}state.content.areas.push({id:`area-${state.content.areas.length+1}`,name:`AREA ${state.content.areas.length+1}`,minX:10,maxX:90,minY:10,maxY:90});renderContent();});
$('#addItem')?.addEventListener('click',()=>{try{syncFromDom();}catch(e){return say(e.message,'error');}state.content.items.push({id:`item-${state.content.items.length+1}`,name:`Item ${state.content.items.length+1}`,kind:'material',description:'',healAmount:0,equipmentSlot:'',damageMin:0,damageMax:0,iconJson:DEFAULT_ICON_JSON});renderContent();});
$('#addMob')?.addEventListener('click',()=>{try{syncFromDom();}catch(e){return say(e.message,'error');}state.content.mobs.push({id:`mob-${state.content.mobs.length+1}`,name:`Mob ${state.content.mobs.length+1}`,maxHp:1,damage:1,attackRange:13,areaId:state.content.areas[0]?.id||'cache-yard',spawnCount:1,respawnTurns:1,killReward:1,drops:[],iconJson:DEFAULT_SLIME_ICON_JSON});renderContent();});
$('#addTerminal')?.addEventListener('click',()=>{try{syncFromDom();}catch(e){return say(e.message,'error');}state.content.terminals.push({id:`terminal-${state.content.terminals.length+1}`,name:`TERMINAL ${state.content.terminals.length+1}`,subtitle:'WORLD TERMINAL',offers:[]});renderContent();});
document.addEventListener('click',e=>{
  const addDrop=e.target.closest('[data-add-drop]'); if(addDrop){try{syncFromDom();}catch(err){return say(err.message,'error');}const mob=state.content.mobs[Number(addDrop.dataset.addDrop)];const first=state.content.items[0]?.id||'';if(!first)return say('Create an item before adding a drop.','error');mob.drops.push({itemId:first,chance:.05,quantity:1});renderContent();return;}
  const removeDrop=e.target.closest('[data-remove-drop]'); if(removeDrop){const card=removeDrop.closest('[data-mob-index]');try{syncFromDom();}catch(err){return say(err.message,'error');}state.content.mobs[Number(card.dataset.mobIndex)].drops.splice(Number(removeDrop.dataset.removeDrop),1);renderContent();return;}
  const addOffer=e.target.closest('[data-add-offer]'); if(addOffer){try{syncFromDom();}catch(err){return say(err.message,'error');}const terminal=state.content.terminals[Number(addOffer.dataset.addOffer)];const first=state.content.items[0]?.id||'';if(!first)return say('Create an item before adding a shop offer.','error');terminal.offers.push({id:`offer-${terminal.offers.length+1}`,direction:'buy',itemId:first,price:1});renderContent();return;}
  const removeOffer=e.target.closest('[data-remove-offer]'); if(removeOffer){const card=removeOffer.closest('[data-terminal-index]');try{syncFromDom();}catch(err){return say(err.message,'error');}state.content.terminals[Number(card.dataset.terminalIndex)].offers.splice(Number(removeOffer.dataset.removeOffer),1);renderContent();return;}
  for(const kind of ['area','item','mob','terminal']){const node=e.target.closest(`[data-remove-${kind}]`);if(!node)continue;try{syncFromDom();}catch(err){return say(err.message,'error');}const index=Number(node.getAttribute(`data-remove-${kind}`));state.content[`${kind}s`].splice(index,1);renderContent();return;}
});
renderContent();
watchIdentity(identity=>{state.identity=identity;const button=$('#createLobby');if(button)button.disabled=!identity?.profileId;say(identity?.profileId?'Ready to create a modular world.':'Sign in to create a lobby.',identity?.profileId?'ok':'');});
